### ISSUE TITLE
Whitelisting doesn't work

### ISSUE THREAD

**Issue by caillette** [lukehutch/fast-classpath-scanner#10]
Nice tool. We needed that. 
Unfortunately whitelisting doesn't seem to work. Could you have a look at those test cases?
https://github.com/caillette/fast-classpath-scanner/commit/0922b9f71d1d0d79a41dc83c6e0e5c3d538fe83c

**Comment by caillette** [comment]
Looking at the code it seems like whitelisting applies only to archive content, not on real directories.

**Comment by lukehutch** [comment]
Ah, sorry about this. I was cleaning up the whitelisting code recently, and must have broken something. I'll try to get this fixed ASAP, although I have a couple of projects that require my time right now, so it might not be for a few days. If you already spotted how to fix it, I'd love a patch.

Also, I appreciate the test code, the lack of tests was always a glaring omission. I'll probably pull your patch into the project as a starting point. If there are other tests you plan to write, or other things you'd like to have tested, that code would be highly appreciated too!

**Comment by lukehutch** [comment]
I added unit tests now and made a new release (sorry for the slight API change in 1.4.0). Thanks for showing how tests should be implemented with JUnit.

**Comment by caillette** [comment]
Thanks, it works, whitelisting made my classpath scan lightning fast. 

I really like the API which preserves fast scanning but remains expressive. 

I just discovered that I should use Javassist instead of Fast-classpath-scanner because in fact I want a dependency tree. The purpose is to calculate a SHA256 fingerprint on the class implementations for financial algorithms that may evolve over time, but must always give the same result for former data. So for each version there is a top-level implementation class, which calculates its fingerprint basing on the byte array of some well-known classes and their subclasses. Alas, using well-known classes requires too much knowledge about my own code, and I'll probably mess it up one day. First I thought that dependency crawling would be a nice feature to add to Fast-classpath-scanner, but it requires full class parsing, which defeats original vision. Javassist is better suited for that. 

I'm happy to have helped with some tests, and I'll probably use Fast-classpath-scanner later for annotation scan.

**Comment by lukehutch** [comment]
If you just need to know if the classes have changed, and if you can trust
timestamps, you can always try this:

https://github.com/lukehutch/fast-classpath-scanner#8-detecting-changes-to-classpath-contents-after-the-scan

This doesn't actually return the last-modified timestamp, so it will only
detect changes between calls to .scan(), but you could add a method that
returned the last-modified timestamp, and store it in a persistent store
somewhere, so that change detection worked across restarts.

Also, the dependency tree (actually, a DAG) is fully built in memory by
FastClasspathScanner, specifically by the class
io.github.lukehutch.fastclasspathscanner.classgraph.ClassGraphBuilder
<https://github.com/lukehutch/fast-classpath-scanner/blob/master/src/main/java/io/github/lukehutch/fastclasspathscanner/classgraph/ClassGraphBuilder.java>.
The field FastClasspathScanner.classGraphBuilder is not currently exposed,
but you could expose it in your own copy of FastClasspathScanner if you
wanted. However, this would only tell you if the class and interface
hierarchy had changed, it wouldn't pick up added/removed fields or methods.
You could also extend FastClasspathScanner to calculate a hash of the first
1kb of each file it read, or something, if you wanted.



On Sat, Jul 25, 2015 at 3:04 AM, Laurent Caillette <notifications@github.com

**Comment by caillette** [comment]
Timestamps are not good for me because they depend on the build date. And the dependencies are just those inside the inheritance tree (plus annotations and including interfaces).

**Comment by lukehutch** [comment]
I added the following methods and released v1.4.1, hopefully they do what
you need:

// Call the following before .scan() (this will slow down
scanning!)public FastClasspathScanner enableHashingClassfileContents()
// Call after scanning, to get a map from classname to MD5 hash of
classfile:public HashMap<String, String> getClassNameToClassfileHash()


On Sat, Jul 25, 2015 at 3:42 AM, Laurent Caillette <notifications@github.com

**Comment by caillette** [comment]
It's a nice feature for change detection. But what I need is a hash over all classes transitively referenced by one class, not only through inheritance and annotation, but also inside the code itself. So it is no longer fast scanning, but slow crawling. I just meant that I'll probably drop FastClasspathScanner for this use case, not because the tool is bad, but because I didn't understand what I truly needed!

**Comment by lukehutch** [comment]
No problem, if it doesn't work for you, there may be a better tool!

I figure that use cases like yours could indicate a real need though, so
that's why I implemented this feature.

One suggestion is the following:

FastClasspathScanner scanner = new FastClasspathScanner(WHITELISTED_PATH);
> scanner.enableHashingClassfileContents().scan();
> List<String> reachableClasses =
> scanner.getNamesOfSubclassesOf(ROOT_NODE_CLASS_NAME);
> // This will find all classes in the transitive closure from the root node
> class.

// Check if reachableClasses has changed since last time you scanned
> (insert code here). If not:
> HashMap<String, String> classNameToHash =
> scanner.getClassNameToClassfileHash();
> for (String className : reachableNodes) {
>     String hashCode = classNameToHash.get(className);
>     // Check if hash code has changed for class (insert code here)
> }


Maybe this still doesn't solve your problem, I don't know if I understood
it :-)  But good luck!


On Sat, Jul 25, 2015 at 7:05 AM, Laurent Caillette <notifications@github.com

**Comment by lukehutch** [comment]
(oops, typo, reachableNodes should say reachableClasses)
