### ISSUE TITLE
Constructor match processor

### ISSUE THREAD

**Issue by weisebrazil** [lukehutch/fast-classpath-scanner#115]
Create a new annotation match processor based using constructors. "ConstructorAnnotationMatchProcessor"

**Comment by lukehutch** [comment]
@weisebrazil Interesting suggestion, but what exactly do you want to match in a constructor? The method signature? Or simply the presence/absence of a constructor?

**Comment by lukehutch** [comment]
@weisebrasil I'm still curious about what you wanted to match?

**Comment by jacospain** [comment]
I would find such a processor convenient to match on the annotations on constructor parameters.

**Comment by lukehutch** [comment]
@jacospain do you want to return all constructors, then manually filter for parameters with a given parameter value?

I'm working on a new API for FCS that will let you do something like the following (methods like `and()` are static imports for clarity):

```java
new FastClasspathScanner().matchClasses().where(
    and(
        method().isConstructor(),
        method().parameters().any().hasAnnotation(SomeAnnotation.class)
    ))
    .call(matchProcessor);
```

..or something like that. If you can wait 2-3 months, I will be releasing this. If not, maybe I can add a constructor match processor in the meantime.

**Comment by jacospain** [comment]
Yes, I'd like to create a binding for a DI framework for every constructor that has a parameter with a given annotation. The match processor API would make this a breeze. I commented because I think this is a prime use case for such a matcher.

The example demonstrating the new planned DSL looks extremely convenient.

I will be able to achieve my desired result with the current API, as well, using mechanism 2 or 3. There is certainly no need for you to add a constructor match processor for me. Thanks!

**Comment by lukehutch** [comment]
@jacospain The current API has become huge and unweildy due to the number of special cases, and cross-products between different things that need matching, so it's long overdue for an overhaul. Given that the current API works well enough, you should probably use that, to avoid the current API getting even more complex. This method will be inefficient though, since you'll have to filter through a larger number of matches than you're interested in. If performance is a problem, please comment back here. I'll keep this bug open to remind myself to add constructor matching to the new API as I create it.

**Comment by jacospain** [comment]
Performance was actually the reason I was interested in this library. 

I swapped your library in for org.reflections:reflections in com.github.racc:typesafeconfig-guice for a huge speed up at application start time! Thanks!

**Comment by lukehutch** [comment]
Glad you're seeing a big performance boost! There should be even better performance once the API changes are in place, because FCS will be able to do a better job of scanning only the things that could potentially match the scan criteria.

**Comment by lukehutch** [comment]
I'll merge this into #111, API Cleanup. Sorry for the delay in getting the new API out, it will still be a couple of months, probably.

@jacospain Note that you can do what you need right now already, using something like the following. Sorry, I should have given this example before.

```java
List<MethodInfo> constructors = new ArrayList<>();
new FastClasspathScanner(packageRoot)
   .matchAllClasses()
   .enableMethodInfo()
   .scan()
   .getClassNameToClassInfo()
   .values()
   .stream()
   .forEach(ci -> ci.getMethodInfo()
       .stream()
       .filter(mi -> mi.isConstructor())
       .forEach(mi -> constructors.add(mi)));

for (MethodInfo mi : constructors) {
    String containingClassName = mi.getClassName();
    for (AnnotationInfo ai : mi.getAnnotationInfo()) {
        // ...
    }
}
```
