### ISSUE TITLE
Computer freezes when scanning

### ISSUE THREAD

**Issue by eduardomaino** [lukehutch/fast-classpath-scanner#119]
When executing these commands on multiple machines (Windows 10) they freeze every time:

`FastClasspathScanner fastClasspathScanner = new FastClasspathScanner();
    List<String> classNames = fastClasspathScanner.verbose(true).scan().getNamesOfClassesImplementing(baseClassName.getName());`

Looking ate the logs I can see a concurrent.ExecutionException: ArrayIndexOutOfBoundsException: 1575 -> FastClasspathScanner.scan : lines 1115, 1143, 1166

I couldn't copy the actual log as my machine freezes every time. Interesting fact is that, if I configure the Java process to use 3 processors, instead of all 4, it works fine. 

Has anyone faced this problem? I'm pointing to the latest version.

**Comment by lukehutch** [comment]
@eduardomaino that's super weird, no Java code should be able to cause a hard lockup, so it looks like a bug in FCS is somehow triggering a JVM bug.

By `FastClasspathScanner.scan` do you mean `FastClasspathScanner.java` with those line numbers? (If so, at least They don't all correspond to source code line numbers in `FastClasspathScanner.java` in git master, what version are you running?)

Can you please attach a screenshot of as much of the backtrace as you can capture? Or maybe try connecting via SSH to capture the log before the machine crashes? (Is there an SSH server for Windows? Or can you try running that new Ubuntu for Windows?)

What JVM version are you running on? Can you try another version, maybe, to rule out the hard lockup as the source of the problems?

Calling `.verbose()` causes significant time and memory overhead. Does the crash occur without `.verbose()`?

The log is generated in memory as a tree, which is only rendered into text at the very end of the run, so if you can see the verbose logs at all, then the point at which the JVM crashes is probably right around the time that the worker threads are shut down.

**Comment by lukehutch** [comment]
Can you also try scanning with one thread? (One of the scan methods has this option.) 

Also, you should consider submitting a snapshot of a complete minimal testcase to Microsoft -- a kernel deadlock or lockup, triggered by user code, is not a good thing! (Unless the code uses lots of RAM, and is merely swapping?)

**Comment by lukehutch** [comment]
@eduardomaino Did you manage to get a backtrace for the `ArrayIndexOutOfBoundsException` by running using a single thread (or over SSH)?

**Comment by lukehutch** [comment]
@eduardomaino The most recent checkin probably fixes the `ArrayIndexOutOfBoundsException` you were encountering (see #121), however I would still like to get to the bottom of the freezing issue on Windows. I don't have a Windows machine to run on, however. Did you make any progress in figuring out why this was freezing? Or were you able to create a minimal testcase that could be submitted to Microsoft or Oracle? Are you sure the OS wasn't just swapping due to sudden increased memory usage or something?

**Comment by lukehutch** [comment]
@eduardomaino I'm going to close this, since I haven't heard back, and the exception issue should be solved now. However, I'm still interested in what triggers the hard lockup. If you can reliably produce the issue with a minimal testcase, using the same version you were on (2.0.21?) please comment here with a link to the minimal testcase, and I'll reopen the bug. Thanks.

**Comment by mgood7123** [comment]
might be freezing due to the OS running out of memory

**Comment by lukehutch** [comment]
Yes, that has to be the cause of lockups. If your scan is taking a lot of memory, you need to think about scanning less, by filtering the classpath, only scanning for info you actually need, etc.
