### ISSUE TITLE
Support http/https entries on classpath 

### ISSUE THREAD

**Issue by bkrahmer** [lukehutch/fast-classpath-scanner#128]
Thanks for sharing this great piece of software!  It's a great utility.  I'm having an issue, though.  I want to dynamically add new jars to a process while it is running.  To do this, I'm getting an instance of the URLClassLoader and calling addURL through reflection, and also updating the java.class.path system property.  If I use Class.forName, I can then get an instance of one of the classes, so I know the JVM class-loading is working with this hackery (jars are from an https url, if it matters).  If I do all of this before calling the FastClasspathScanner the first time, it also finds the classes.  However, if I call FastClasspathScanner.scan() once, modify the classpath, and then create a new instance and scan again, I don't see the newly added classes.  This implies some sort of caching is going on.  Do you know of any simple workarounds?  I didn't see anything in the docs.

**Comment by bkrahmer** [comment]
Maybe I will just go a different route on this.  I felt like adding jars to the classpath would be the easiest approach, but strictly speaking for my use case, I don't need the classes.

**Comment by lukehutch** [comment]
@bkrahmer Sorry for the delay, I have been in the process of moving to another apartment. 

FastClasspathScanner doesn't do any sort of caching in static fields. However, many ClassLoaders do their own caching, including the JVM system classloader. That doesn't seem to fully explain the problem you're seeing though, because you're seeing instances of classes not being found at all -- which is strange.

One thing I should point out is that defining your own `URLClassLoader` is quite dangerous: if your custom `URLClassLoader` loads an instance of a subclass, and the system classloader has already loaded and cached the class' superclass, casting an instance of the subclass to the superclass can give a runtime `ClassCastException`. You can also end up with cases where the same class can be loaded twice by different classloaders, and instances of those classes are deemed of different type by the runtime. (This is only two of several nasty issues that can occur...)

In a later version of FastClasspathScanner, I'm going to make it possible to scan any classpath for classes or files without enabling classloading. You can actually already do this by calling `.overrideClasspath(String cp)` -- but all the above caveats apply if you try loading classes with this scan override method, e.g. if you use `MatchProcessors`. However, if you are just using a `ScanResult` to get the names of matching classes, no classloading occurs, so this is totally safe.

If you can please provide a bit more detail though, I'd like to dig further into why this wasn't working for you, since I think there may be something useful to learn here, and I'd like FCS to work for as many unusual cases as possible. Thanks!

**Comment by bkrahmer** [comment]
Hi Luke.  Thanks the reply.  It's great to see your interest in my issue.  I know the dangers of creating my own classLoader, so I was trying to avoid that.  I'll append my unit tests here which I think clearly illustrate the issue.  I had missed overrideClasspath, but now that I've added it, it had no effect.  Looking forward to your analysis.

thanks,
brian

`@Test
    public void testGetServiceDefinition() throws ClassNotFoundException {
        String serviceName = "com.sixt.service.journey";
        Map<String, String> protoFiles = apiLoader.getServiceProtoFiles(serviceName); //modifies classpath
        assertThat(protoFiles).hasSize(1);
        assertThat(protoFiles.keySet()).contains("journey.proto");
        Class<?> responseClass = Class.forName("com.sixt.service.journey.api.JourneyOuterClass$ReserveVehicleCommand");
        assertThat(responseClass).isNotNull();
        FastClasspathScanner cpScanner = new FastClasspathScanner();
        ScanResult scanResult = cpScanner.scan();
        List<String> oldProtobuf = scanResult.getNamesOfSubclassesOf(GeneratedMessage.class);
        List<String> newProtobuf = scanResult.getNamesOfSubclassesOf(GeneratedMessageV3.class);
        assertThat(oldProtobuf.size() + newProtobuf.size()).isGreaterThan(0);
    }

    @Test
    public void testClassPathChanging() throws ClassNotFoundException {
        FastClasspathScanner cpScanner = new FastClasspathScanner();
        ScanResult scanResult = cpScanner.scan();
        List<String> oldProtobuf = scanResult.getNamesOfSubclassesOf(GeneratedMessage.class);
        List<String> newProtobuf = scanResult.getNamesOfSubclassesOf(GeneratedMessageV3.class);
        int sizeBefore = oldProtobuf.size() + newProtobuf.size();

        String serviceName = "com.sixt.service.journey";
        Map<String, String> protoFiles = apiLoader.getServiceProtoFiles(serviceName); //modifies classpath
        assertThat(protoFiles).hasSize(1);
        assertThat(protoFiles.keySet()).contains("journey.proto");
        Class<?> responseClass = Class.forName("com.sixt.service.journey.api.JourneyOuterClass$ReserveVehicleCommand");
        assertThat(responseClass).isNotNull();
        cpScanner = new FastClasspathScanner().overrideClasspath(System.getProperty("java.class.path"));
        scanResult = cpScanner.scan();
        oldProtobuf = scanResult.getNamesOfSubclassesOf(GeneratedMessage.class);
        newProtobuf = scanResult.getNamesOfSubclassesOf(GeneratedMessageV3.class);
        int sizeAfter = oldProtobuf.size() + newProtobuf.size();
        assertThat(sizeAfter).isGreaterThan(sizeBefore);
        assertThat(oldProtobuf.size() + newProtobuf.size()).isGreaterThan(0);
    }`

Here is part of the function referenced, which does the actual modification of the classpath.  Again, this is a jar from an https server (no authentication required)

`private void addJarToClassPath(URL inputURL) {
        Method method;
        try {
            method = URLClassLoader.class.getDeclaredMethod("addURL", URL.class);
            method.setAccessible(true);
            method.invoke(ClassLoader.getSystemClassLoader(), inputURL);
            String classPath = System.getProperty("java.class.path");
            System.setProperty("java.class.path", classPath + ":" + inputURL.toString());
        } catch (Exception e) {
            logger.warn("Caught exception adding jar to classpath", e);
        }
    }`

**Comment by lukehutch** [comment]
@bkrahmer nice to know my code is being used by Sixt -- I rented one of your cars recently in Norway :-)

FCS doesn't currently support non-local classpath elements. I was wondering if I'd ever run into cases where users need to include jars over http(s), but you're the first one that has reported this so far. Technically the spec allows it, but due to efficiency considerations, I have never seen anyone try to do this before now!

So now that I understand that you're compiling protobuf definitions on the fly, it makes sense that you would want to modify the classpath at runtime. You're really taking Java places it wasn't really designed to go though, based on the caching mechanisms built into the system classloaders! To get this to work well, you might need to pull in some sort of third-party dynamic classloader mechanism that is able to not only load classes, but hot-replace instances of classes that are already loaded. [This is a complex topic, however...](http://tutorials.jenkov.com/java-reflection/dynamic-class-loading-reloading.html)

As far as why FCS doesn't find the classes after you modify the classpath -- it's hard to say without looking at the logs. Can you please generate logs for the two different scan attempts (the one that works and the one that doesn't, with all other things being equal), by calling `.verbose()` before `.scan()`, and attach them here?

**Comment by lukehutch** [comment]
PS please also let me know if you really do need to access classpath elements over https, maybe I need to add that capability. It's not ideal though, since it will cause the jar to have to be fetched more than once -- once by FCS, once by the classloader if/when the classes are loaded.

**Comment by bkrahmer** [comment]
I changed my code to download the jar, and added that to the classpath.  It works!  Thanks for the help!
brian

**Comment by lukehutch** [comment]
Great, I'm glad it works now! I should probably throw an exception if http(s) elements are discovered on the classpath, rather than failing silently. Or maybe I should just allow this, with the performance caveat. I'll reopen this as a reminder to fix this.

**Comment by lukehutch** [comment]
Note to self: Need to abstract away NestedJarHandler to be able to handle other temporary file types too, and then implement jar downloading for http/https classpath entries.

**Comment by lukehutch** [comment]
I just noticed this old bug report, and I should circle back and say that http(s) classpath elements have been supported in ClassPath (formerly FastClasspathScanner) for over a year now.
