### ISSUE TITLE
Ability to obtain class files as byte[]

### ISSUE THREAD

**Issue by bbusching** [lukehutch/fast-classpath-scanner#14]
I want to be able to access the class file byte arrays of certain classes on my classpath so that I can load them using sun.invoke.anon.AnonymousClassLoader. I really like the utility this classpath scanner provides and I can override the loadClass method, but there is no easy mechanism for obtaining the byte [] of my class. Is it possible to make scanZipfile a protected method so that I can override it's implementation to convert the input stream into a byte array before reading the contents?

**Comment by lukehutch** [comment]
Good question. If you don't mind using a path to a classfile, rather than the name of the class you're interested in, you can do this already by adding a FileMatchProcessor with .matchFilenamePattern():

https://github.com/lukehutch/fast-classpath-scanner#6-finding-files-even-non-classfiles-anywhere-on-the-classpath-whose-path-matches-a-given-regular-expression

Your FileMatchProcessor will be passed an InputStream to either the file on disk or the zipfile entry for any file whose relative path matches the regexp. So you'd basically use something like "^com\\.pkg\\.MyClass\\.class$" or similar as your pattern, then read from the InputStream into a byte buffer, then convert into a byte[] array.

If you want to be able to apply some matching criteria first (e.g. only dynamically load subclasses of a given class), then you'd use two separate FastClasspathScanner instances: one to do the matching (just instantiate the scanner, call scan(), then call .getNamesOfSubclassesOf("com.pkg.SuperClass")), then a second scanner to load the bytes of the matching classes as described above.

Does that work for you? I'm open to the possibility of adding byte loading to the scanner itself, if there's a compelling enough usecase. (I added something similar recently for another user -- see the methods enableHashingClassfileContents(), getClassNameToClassfileHash() and hashInputStream() in FastClasspathScanner.java.)

**Comment by lukehutch** [comment]
PS I hadn't heard of sun.invoke.anon.AnonymousClassLoader before, and I'm curious if it gets around some of the issues described here:

http://tutorials.jenkov.com/java-reflection/dynamic-class-loading-reloading.html

**Comment by bbusching** [comment]
I will give your suggestion a try, but I would love it if you had the time to add byte loading. If it turns out that I need a little quicker access to the class files, I will probably just fork this and add functionality similar to enableHashingClassfileContents().

PS. I'm no expert at classloaders but I'm using the AnonymousClassLoader to hopefully make the garbage collection of dynamically loaded classes better so that that when I dyncamically reload them, the JVM isn't blowing up.

**Comment by lukehutch** [comment]
enableHashingClassfileContents() is pretty much exactly what I described, only implemented inside the main class itself, rather than as a FileMatchProcessor -- so I think you can do what you need to with just a few lines of code. Did my explanation make sense? If not, let me know and I'll write out some pseudocode.

I'll close this for now, but feel free to keep commenting...

**Comment by bbusching** [comment]
I would appreciate pseudocode.

As I'm understanding, I  agree that enableHashingClassfileContents() is very much like what I want just instead of hashing the file, I want to load a class using the input stream and store that. I was hoping to not have to make edits to any of the files you provide to make maintaining this as a dependency easier.

**Comment by lukehutch** [comment]
Actually, I guess you can do it with a single FastClasspathScanner instance, since there's no reason you can't add more MatchProcessors between scans. Try something like the following (untested, this is just typed straight into the editor, so there may be mistakes). Let me know if this works:

--

FileMatchProcessor fileMatchProcessor = new FileMatchProcessor() {
    public void processMatch(String absolutePath, String relativePath, InputStream inputStream) throws IOException {
        String className = relativePath.substring(relativePath.length() - 6) // strip off ".class"
                                    .replace('/', '.');
        byte[] classfileContents = IOUtils.toByteArray(inputStream);
        myClassLoader(className, classfileContents);   // Do the class loading here
    }
}

FastClasspathScanner scanner = FastClasspathScanner("com.pkg"); // Put package root here
List<String> mySubclasses = scanner.scan().getNamesOfSubclassesOf("com.pkg.MySuperclass");
for (String subclassName : mySubclasses) {
    String subclassPathPattern = "^" + subclassName.replace('.', '/').replaceAll("$", "\\$") + ".class$";
    scanner.matchFilenamePattern(subclassPathPattern, fileMatchProcessor);
}
scanner.scan();

**Comment by bbusching** [comment]
This did not work for me. I suspect scanZipfile to be the reason:
starting at line 1097, scanZipfile will only do filenamePattern matching if the file does not end with ".class"

if (path.endsWith(".class")) {
  // Found a classfile, open it as a stream and inspect header
  try (final InputStream inputStream = zipFile.getInputStream(entry)) {
    readClassInfoFromClassfileHeader(inputStream);
  }
  if (classNameToClassfileHash != null) {
    // Hash the contents of the classfile, if requested
    try (final InputStream inputStream = zipFile.getInputStream(entry)) {
      hashInputStream(path.substring(0, path.length() - 6).replace('/', '.'), inputStream);
    }
  }
 } else {
  // For non-classfiles, match file paths against path patterns
  for (final FilePathMatcher fileMatcher : filePathMatchers) {
    if (fileMatcher.pattern.matcher(path).matches()) {
      // There's a match -- open the file as a stream and
      // call the match processor
      try (final InputStream inputStream = zipFile.getInputStream(entry)) {
        fileMatcher.fileMatchProcessor.processMatch(path, path, inputStream);
      }
    }
  }
}

**Comment by lukehutch** [comment]
Oh, you're totally right, good catch. OK, I'll try to work on this tonight or tomorrow night.

(Note to self, I hit this when adding hashInputStream() as well, I should unify the two usecases somehow...)

**Comment by lukehutch** [comment]
OK, I think you'll be happy with the changes I just pushed -- all you need to do now is:

```java
new FastClasspathScanner("com.pkg")
    .matchFilenameExtension("class", new FileMatchProcessor() {
        public void processMatch(String relativePath, byte[] classfileContents) throws IOException {
            myClassLoader(classfileContents);   // Do the class loading here
        }
    }).scan();
```

Please test this, and I'll push a release out to Maven in a day or two.

**Comment by bbusching** [comment]
From an initial glance, it looks great. I should get around to trying it out this afternoon and I'll let you know the results.

**Comment by lukehutch** [comment]
Sounds good.

Check the docs for other ways to match, e.g. you can search for non-regexp strings now:

https://github.com/lukehutch/fast-classpath-scanner#6-finding-files-even-non-classfiles-anywhere-on-the-classpath-whose-path-matches-a-given-string-or-regular-expression

You'd still want to use the initial pattern I suggested of two scanning phases, if you want to find classes that meet certain criteria (e.g. scan for subclasses of a given class, then for each one, call .matchFilenamePath with your FileMatchContentsProcessor), then call scan() again the second time.

If performance is important, and you can end up generating a lot of classes that need reloading, then the method I proposed might be a bit slow, since every classname will be checked against every class, and the complete byte[] contents of every classfile will be loaded whether or not it's a matching class. To optimize this, you should store the matching classnames in a HashSet<String> during the first scan, then only add a single FileMatchProcessor (not a FileMatchContentsProcessor) using .matchFilenameExtension("class", new FileMatchProcessor() { /*...*/ }). The processMatch method will be passed a relative path, an InputStream and a stream length. First convert the relative path into a classname, then check if the classname is in the HashSet of matching classes. If not, just return without reading from the InputStream. If it does match, read the InputStream into a byte[] array, and call the classloader.

**Comment by bbusching** [comment]
From the little initial tests, I have been able to do it is working great! Thank you very much.

**Comment by lukehutch** [comment]
Great, thanks for testing. If there are new problems, feel free to open a new bug.
