### ISSUE TITLE
Unknown constant pool tag in classfile module-info.class 

### ISSUE THREAD

**Issue by wuetherich** [lukehutch/fast-classpath-scanner#141]
Currently the fast-classpath-scanner fails for JPMS modules, as the Java 9 Spec defines two additional constant pool tags for module-info classes (see https://docs.oracle.com/javase/specs/jvms/se9/html/jvms-4.html#jvms-4.4): CONSTANT_Module (19) and CONSTANT_Package (20).

**Comment by lukehutch** [comment]
@wuetherich Thanks for finding and reporting this, and thanks for the associated PR #142.

The PR is great for now. However, for full JDK9 support (#36), I'm guessing that at least `CONSTANT_Package` will probably have to be parsed, since I'm guessing that allows JDK 9 to break the requirement that classfiles paths match the package name, or something?

**Comment by lukehutch** [comment]
@wuetherich PS if you know anything about JDK9, I would love your comments on #36. I have yet to dive headlong into that.

**Comment by lukehutch** [comment]
Published in 2.6.1. Please also see comments/questions above. Thanks!
