### ISSUE TITLE
Access to typeDescriptor within FieldInfo and MethodInfo

### ISSUE THREAD

**Issue by chrisr3** [lukehutch/fast-classpath-scanner#144]
Can you provide accessor functions for `FieldInfo.typeDescriptor` and `MethodInfo.typeDescriptor` please? I am trying to write simple comparators for both of these classes, and `typeDescriptor` is clearly a key field. I definitely don't need all of the repeated "cooking" of the value that all of the existing accessors would provide.

Failing that, maybe `FieldInfo` and `MethodInfo` could just implement `Comparable`, like `ClassInfo` already does?

**Comment by lukehutch** [comment]
Done -- funny thing though, I added `getTypeDescriptor()` just a few days ago, then I removed it again because I thought, "Nobody will ever need this" :-)

Please test the above checkin... in particular, please let me know if you think I should add the class name to the comparison too. (In `java.lang.reflect` at least, `Field` and `Method` are tied to a specific class, so maybe I should replicate those semantics here.)

**Comment by lukehutch** [comment]
I added code to use class name for the `equals()`, `compareTo()` and `hashCode()` methods.

I think this is all fixed and implemented as of the latest commit, so I'll close this, but please let me know if it doesn't do what you need. I'll be pushing out a new version with these changes. Thanks for the report!

**Comment by lukehutch** [comment]
Released in 2.7.0.
