### ISSUE TITLE
Need a better way to do filtering

### ISSUE THREAD

**Issue by GedMarc** [lukehutch/fast-classpath-scanner#161]
Hey Luke,

I've hit a bit of a bad practice with regards to black-listing, not sure if there is a better way (a root properties class perhaps? or a meta-inf/service injection?)

Take a look at https://github.com/GedMarc/GuiceInjection/blob/master/src/za/co/mmagon/guiceinjection/GuiceContext.java from Line 450.

I'm building a JEE framework based on Guice, when running on various EE platforms (Glassfish, JBoss, EAP, Tomcat, etc) there are a lot of libraries that should be excluded from the scan. Including the full filter for all the EE environments this list gets very very ugly.

Any suggestions or progressions on how this can be cleaned up?

**Comment by lukehutch** [comment]
Hi @GedMarc, shouldn't you be whitelisting the things you *do* want to scan, rather than blacklisting the things you *don't* want to scan? If anything is whitelisted, that means everything else is blacklisted by default. 

Other than that, can you suggest some other filtering mechanism that would work for you?

**Comment by lukehutch** [comment]
I think this issue is now a dup of #162? Should this one be closed?

**Comment by GedMarc** [comment]
Closed by #164
