### ISSUE TITLE
Whitelisting

### ISSUE THREAD

**Issue by GedMarc** [lukehutch/fast-classpath-scanner#162]
Hey Luke

I'm trying to get the white listing working as the black listing still takes quite a while :)
When using the white list in my tests - nothing comes up,

Am I doing something wrong? From what I can see I am matching your documentation

[servicelocatortest.zip](https://github.com/lukehutch/fast-classpath-scanner/files/1578576/servicelocatortest.zip)

**Comment by lukehutch** [comment]
I see you have the source set to 1.8 in Maven, but are you running this on JDK 9? I have found an issue with the way I'm getting paths from the JDK 9 classloader.

**Comment by GedMarc** [comment]
Naw running JDK 8 only

**Comment by lukehutch** [comment]
OK, so I took a look on JDK 8. The issue is that scanSpec strings with wildcard globs like `*.xml` are not supported currently (the scanSpec is used to specify packages, classes and jars, not filenames). You need to use a `FileMatchProcessor` to match files with wildcards, or with a given extension etc.

However, there is another issue. Whenever even one package is whitelisted, then everything but what's in the whitelist is blacklisted by default. That means that by specifying the package `test` in the whitelist, you exclude the default (unnamed) package from consideration. However, if you were to provide `""` as a whitelisted package prefix, everything would be scanned, because the default package is a parent of all packages.

Therefore, there needs to be some special configuration flag or scanSpec setting that says "scan things in the default package, but don't recurse into sub-packages unless they are whitelisted". I'll have to add that, since this seems like a common requirement.

**Comment by lukehutch** [comment]
@GedMarc Please test the master version -- add `FastClasspathScanner#alwaysScannClasspathElementRoot()` to your code before the scan.

**Comment by GedMarc** [comment]
Looks good,

**Comment by lukehutch** [comment]
Looks good meaning it solves the problem? Please be more specific :)

**Comment by lukehutch** [comment]
Based on your comment in the other bug, I'll assume this is fixed.

**Comment by lukehutch** [comment]
Released in 2.9.4.
