### ISSUE TITLE
Expose classpathElementOrderURLs

### ISSUE THREAD

**Issue by rupebac** [lukehutch/fast-classpath-scanner#164]
I am very interested in your library to solve a typical problem. Fetching the effective classpath. I have two suggestions to make, and would like to know what you think about them:

1) I have seen that `ScanResult `exposes `public List<File> getUniqueClasspathElements() ` but there is no getter for `classpathElementOrderURLs`. I think it makes sense you stop working with `File`, and move to things like `Path`, or just plain `URL`. For us, that we work exclusively with `Path `(as you can better unit test it), is seems unnecessary having to transform the output of your library.

2) I see that the classpath fetching is very much inside the Scan. Now, I am not really interested on requesting a full scan, just to fetch the classpath. I suspect the performance difference to be huge. Why dont you extract the functionality to fetch the classpath into a different artifact?

Thanks for your code. It is very useful.

**Comment by lukehutch** [comment]
Hi @rupebac,

I agree that fetching the effective classpath is a major usecase for FCS. It has been a lot of work to get FCS to work with the myriad of classpath specification mechanisms that exist out there in the wild, and nobody should have to repeat that work.

There are several reasons that I didn't just return the raw URLs obtained from the classloaders. Currently, `getUniqueClasspathElements()` is guaranteed to only return `File` classpath elements that actually exist, and that pass file canonicalization (i.e. where there is no exception thrown during canonicalization). The reason it passes through `Scanner` is that canonicalization can be very time consuming on some filesystems -- in benchmarks, it amounted to quite a significant percentage of total scan time for some scanning workloads -- so I wanted to fully parallelize all the canonicalizations. (Canonicalization is required to find duplicate classpath elements, as well as elements that are rooted within other classpath elements, to eliminate duplicated scanning, among other things.) Also, if a classpath URL is a reference to a jar within a jar, then the inner (or innermost) jar is extracted to a temporary file, and the path to that innermost file is returned to the caller. Similarly, any `http(s)://` URLs on the classpath are fetched to temporary files before being returned. This happens right before the canonicalization step, and is also performed in parallel. And, importantly, a jar manifest file can contain a `Class-Path:` entry that pulls another jarfile into the classpath, so to get the whole classpath, you actually have to have physical access to every jarfile on the classpath (including jars within jars, and remote jars). Manifest file reading is also parallelized.

In `Scanner.java` line 301, you will see `if (enableRecursiveScanning) { ... }` -- a full scan is not performed if you are only getting classpath elements. So in general, if you are only interested in the actual classpath elements, you are only paying the cost of canonicalization and testing for file existence.

Ultimately you should test the performance of the call as it is implemented, and if there are performance issues, please let me know. I think you'll find that the call is generally very fast, since none of the classpath elements are actually opened for reading, except to read the manifest file in the case of jars.

You're right though, I had meant to add `getUniqueClasspathElementURLs()`, but forgot to do so when I added that field to `ScanResult`. That method is now in both `ScanResult` and `FastClasspathScanner` in git master.

If you want just the raw URLs reported by the classloaders, I could also provide a function for fetching these, but they don't provide the full picture, since additional `Class-Path:` manifest entries may be present somewhere in the classpath. I don't think it makes sense to report the raw URLs.

Also, just as a heads-up, I'm working on adding Java 9 support in the near future, and for modules, there really isn't a concept of classpath URLs anymore (you can get a module URI, but it's not a real URL), so I'm not sure how this will affect the API.

**Comment by lukehutch** [comment]
PS the reason I don't work with `Path` is because it is a horribly slow and inefficient API. I benchmarked the heck out of a range of systems for working with paths, files and URLs, and `Path` was really slow in some cases, so I don't even use it internally, except in one or two cases where it was necessary.

**Comment by rupebac** [comment]
Alright. Thanks for the explanation. It makes fully sense now. I did not think on canonicalization.
 I was not aware of the inefficiency of the Path implementation in Java 8. 

As you have explained I do not think it makes much sense to add support to return the URLs as it from the class loaders.

Interesting discussion about NIO vs IO performance:

https://stackoverflow.com/a/7611531/1043677

Feel free to close the issue.
Thanks!

**Comment by lukehutch** [comment]
Path is probably not particularly inefficient given all that it does, and it's a nice API (perhaps the only nice way to deal with paths and URLs in a unified way in Java). But there are just faster ways to get the job done when you care about speed, and when you're processing a large number of paths.

Thanks for reporting, will close the issue. I'm pushing out version 2.9.4 now with the additional API calls.
