### ISSUE TITLE
Error "Could not find a ClassLoaderHandler that can handle AntClassLoader"

### ISSUE THREAD

**Issue by jacobg** [lukehutch/fast-classpath-scanner#170]
I just switched out Reflections for fast-classpath-scanner due to multi-threaded issues with reflections. Our scala tests run using an ant task are failing with fast-classpath-scanner due to not finding certain expected classes. In verbose mode, I see this warning:

`[ant:scalatest] 2018-01-18T16:21:04.913-0500    FastClasspathScanner    ------ Could not find a ClassLoaderHandler that can handle AntClassLoader[....`

One of the class directories listed in the AntClassLoader contains classes that are missing from the scan.

Is AntClassLoader supported by fast-classpath-scanner? It used to work in reflections, although I don't see any code in reflections specifically to support Ant.

**Comment by jacobg** [comment]
Looks like registering this class handler fixes it:

`
public class AntClassLoaderHandler implements ClassLoaderHandler {

	public static final String[] HANDLED_CLASSLOADERS = { "org.apache.tools.ant.AntClassLoader" };

	@Override
	public DelegationOrder getDelegationOrder(ClassLoader classLoaderInstance) {
		return DelegationOrder.PARENT_FIRST;
	}

	@Override
	public void handle(ScanSpec scanSpec, ClassLoader classLoader, ClasspathOrder classpathOrderOut,
	                   LogNode log) throws Exception
	{
		classpathOrderOut.addClasspathElements( //
				(String) ReflectionUtils.invokeMethod(classLoader, "getClasspath", false), classLoader, log);
	}
}
`

Just curious, why didn't you define a handledClassLoaders method on the interface rather than require the field HANDLED_CLASSLOADERS?

**Comment by lukehutch** [comment]
@jacobg Thank you for this report, and for the code to fix the issue. It's quite surprising that nobody else has hit this yet (or at least reported it)! It's also surprising that Reflections had no issue with this classloader, but that makes me think that I also need to be trying a range of different predictable method names and field names (such as `getClasspath()`) to get the classpath as a fallback, which I'm going to implement now. I assume this is what Reflections does too, since it doesn't have custom code for too many nonstandard classloaders.

As far as the static field -- yes, it's weird, and I set it up that way for historical reasons that I don't actually remember right now, back when there was only a single method (`handle()`). Now that there's another method in the interface, it makes sense to break the API to make the list of handled classloaders into an interface method too. I just barely broke the `ClassLoaderHandler` interface yesterday, so I think now's the time to do it again. (I don't know of anyone defining their own `ClassLoaderHandler`, but in case there are instances of that, it will probably minimize disruption to do it soon.)

I'll push this change out shortly.

**Comment by lukehutch** [comment]
@jacobg Oh, I remember the reason for the static field now. Java does not have the ability to specify required static methods in interfaces, and I wanted to be able to query each of the `ClassLoaderHandler` classes to get the list of `ClassLoader` names that they handle, without instantiating the `ClassLoaderHandler`. (One `ClassLoaderHandler` will be instantiated for each `ClassLoader`, but by returning the handled `ClassLoaderNames` from an interface method, I would need to instantiate each `ClassLoaderHandler` one additional time at initialization, just to get the list of supported `ClassLoader`s.) This would also be kind of ugly. But maybe the lesser of two evils is to return the `ClassLoader` names from a method, and do the extra instantiation.

**Comment by lukehutch** [comment]
Released in 2.11.0. Thanks again!

**Comment by jacobg** [comment]
Thanks so much Luke for the engagement and fast turnaround! When will 2.11 be on Maven?

**Comment by lukehutch** [comment]
@jacobg I pushed 2.11.0 out last night. I just double-checked, and it's in Sonatype, although it usually takes a few hours to make it to Maven Central. You may have to update your Maven index if you can't see it yet.

**Comment by lukehutch** [comment]
@jacobg Yeah, Maven Central is really slow at updating :-)  Let me know if you come across any other issues!
