### ISSUE TITLE
Error when trying to get method name for methods with generics

### ISSUE THREAD

**Issue by anthonykr3** [lukehutch/fast-classpath-scanner#172]
I am getting an error when trying to reconstitute the method name for a generic method with the following signature:

public <T> TestB<T> toTestB(TestC<T> other)

The error is:
`Type signature could not be parsed: <T:Ljava/lang/Object;>(Lio/github/lukehutch/fastclasspathscanner/issues/issue199/a/TestC<TT;>;)Lio/github/lukehutch/fastclasspathscanner/issues/issue199/a/TestB<TT;>; (position: 0)`

It looks like parseComplexTypeDescriptor doesn't accept type descriptors beginning with < - I've recreated the issue as a test in this fork [here](https://github.com/anthonykr3/fast-classpath-scanner)

Log file:
[log.txt](https://github.com/lukehutch/fast-classpath-scanner/files/1659419/log.txt)

**Comment by lukehutch** [comment]
@anthonykr3 Many thanks for your report, and for the test case! Strangely, your test case didn't fail on my machine (maybe because ecj compiles the code slightly differently than javac), but I was able to reproduce using the type string in the error message you sent. The fix will be in the next release, version 2.12.0, which should be out in an hour or two.

**Comment by anthonykr3** [comment]
Thanks so much for the speedy response!

**Comment by lukehutch** [comment]
You're welcome!
