### ISSUE TITLE
build-time scanning

### ISSUE THREAD

**Issue by cvmocanu** [lukehutch/fast-classpath-scanner#184]
[Reflections](https://github.com/ronmamo/reflections) has a really nice feature that [allows scanning at build time](https://github.com/ronmamo/reflections/blob/gh-pages/UseCases.md#collect-pre-scanned-metadata).
Then, at runtime one can simply load the saved file instead of scanning the classpath.

This is significantly faster than scanning the classpath.

It would be really nice for fast-classpath-scanner to support this.

In addition, I see that Reflections is using XML with dom4j to save the scanning result.
It would be nice for fast-classpath-scanner to use a lighter/faster approach (e.g. protobuf).

**Comment by lukehutch** [comment]
This is a good suggestion. This would be useful on Android too (#24). It will be quite a lot of work, so it may take a while, but I'll look into it.

**Comment by lukehutch** [comment]
I started looking at this, but one issue that jumped out pretty quickly is that when serializing a set of `ClassInfo` objects, the information about which `ClassLoader` was supposed to load each class would be lost (there is no point serializing the reference to the appropriate `ClassLoader` into the output stream, since in general the scanning/serializing and reloading will happen in different runtime instances). You could still try to load classes by name, but it can and probably will sometimes break, and you get to keep the pieces. (Basically you will have to be really sure that the classpath at build time and runtime are exactly the same.)

This may sound like an esoteric problem, but similar things have been the source of a number of bug reports in the past, primarily in cases where the same class was defined multiple times on the classpath, and the version that FCS found was different than the version the classloader found, because the classpath had been overridden or something.

**Comment by andrebrait** [comment]
Maybe something like what https://github.com/atteo/classindex did would work? It seems he uses annotation processing for that.

It seems to be insanely fast too. But writing an annotation processor can be a bit too much and may not work sometimes.

**Comment by lukehutch** [comment]
@andrebrait thanks, that's a useful link. I'll have to look at how their mechanism works.

There are some more links on JSR-269 processing here: https://ilikeorangutans.github.io/2013/08/13/jsr-269-annotation-processing/

But actually the simplest thing to do is something like the following, once FCS supports serializing a ScanResult out to disk -- just add a small Groovy script to perform the scan and save the result, inside a Maven post-build rule: https://stackoverflow.com/a/20772596/3950982

Would that Maven trick work for everybody that cares about build-time scanning?

**Comment by andrebrait** [comment]
@lukehutch I believe it would, yes.

Making it compatible with Gradle should be easy, right? Adding a task in Gradle or even making a small gradle plugin, maybe?

**Comment by lukehutch** [comment]
@andrebrait Probably, if there's a simple Gradle plugin example that could be extended. (Feel free to take a shot at this yourself, if you want -- I have never used Gradle!)  But see the comment at the page linked below about why the Reflections Maven plugin was discontinued -- it was just much easier to write a one-line Groovy script, using the gmavenplus-plugin Maven plugin:

https://github.com/ronmamo/reflections-maven

Maybe Grail has a similar mechanism for adding short snippets of code inline in the build rules?

**Comment by andrebrait** [comment]
@lukehutch Yeah, Gradle probably has a way for that (Gradle is basically Groovy in a build system, so I would ve surprised if it doesn't).

And you should use Gradle sometime. I've used Maven for years, and while I like it, Gradle is so much easier and flexible. I can see why people have been switching to it thenlast few years.

Anyway, I'll see if that's doable and, if so, I'll contribute with instructions on how to do that once the Groovy script is done :)

**Comment by lukehutch** [comment]
I don't doubt it's better -- Maven is completely awful! :) I'd be happy to switch to Gradle at some point.

**Comment by seanf** [comment]
> There are some more links on JSR-269 processing here:
https://ilikeorangutans.github.io/2013/08/13/jsr-269-annotation-processing/
https://www.youtube.com/watch?v=2Dlo8OSwzaI
>
> But actually the simplest thing to do is something like the following, once FCS supports serializing a ScanResult out to disk -- just add a small Groovy script to perform the scan and save the result, inside a Maven post-build rule: https://stackoverflow.com/a/20772596/3950982
>
> Would that Maven trick work for everybody that cares about build-time scanning?

That wouldn't work in IDEs (or not easily), but as long as it can fall back on a runtime scan, I think it would be fine.

**Comment by lukehutch** [comment]
The first half of this is done -- you can now serialize a class graph by calling `ScanResult#toJSON()`, which is a fast and lightweight custom JSON serializer. I still need to write a deserializer.

**Comment by andrebrait** [comment]
@lukehutch you probably looked into it, but using a JSON library would probably result in unnecessary dependencies, right? Like GSON, Jackson, etc.

And for the second part, I'll see what I can do to produce a Gradle plugin. If I can also make one for Maven, I think 99% of everyone who uses this library would be covered.

**Comment by lukehutch** [comment]
@andrebrait yes, of course -- but FCS doesn't require any dependencies right now, and I'm resisting adding the first one :-)  Plus I have found libraries like GSON and Jackson to be heavyweight and hard to configure and use in the past. I have a very specific usecase here (serializing the ClassInfo object graph) that is unlikely to change much in the future, and so I figured I'd design a custom serializer and deserializer. Also, the object graph has cycles, which are not generally handled well in JSON serialization libraries (since JSON doesn't have innate support for references or pointers), so I need to treat that carefully, adding to the need for custom serialization and deserialization.

**Comment by lukehutch** [comment]
@andrebrait yes, an early working version of the serializer is in master, and it handles cycles (by adding "_ID" fields to objects, then detecting cycles, and inserting object references where necessary). I have a more advanced version in the works that allows you to tag up a field to use as a unique object id, rather than the automatically-generated id (specifically so references to ClassInfo objects can use the class name instead of a number).

I will need to write a smart deserializer too, but at least you'll be able to play with generating the serialized output, and saving it to a project's resource directory during build. Just call:

```String jsonStr = new FastClasspathScanner(packageName).scan().toJSON();```

**Comment by lukehutch** [comment]
The new serializer (just committed) is much better than the old one, and hopefully is complete.

**Comment by andrebrait** [comment]
Ok, cool. I'll grab your code as soon as I have something thsti works with GSON for testing purposes.

Basically, including FSC in Gradles's buildscript dependencies and using it will dp the trick.

No clue about Maven though.

**Comment by andrebrait** [comment]
So, I got something working with Gradle. But I'm having some trouble with the classpath. As I understand  I need to have the classes to be scanned in the classpath at the moment of the scan, is that right?

**Comment by lukehutch** [comment]
@andrebrait You will want to set up a Gradle rule that determines the _runtime classpath_, and then scans that. This may be different than the build-time classpath, because, for example, build tools will no longer be on the classpath. Also, it will be different in general than the testing classpath (or other non-deployment action classpaths), because testcases might run with additional libraries.

If you can find the runtime classpath as a string or list of paths, you can call e.g. `ScanResult scanResult = new FastClasspathScanner(package).overrideClasspath(runtimeClasspath).scan()` .

**Comment by lukehutch** [comment]
OK, I just committed the JSON serialization and deserialization work. If you ever want to lose a lot of hair, then write a POJO serializer and deserializer from scratch! I thought I knew most of the warts of the Java type system, but this (self-inflicted) task gave me a whole new level of appreciation for it...

Please test with the following, with the version in master, and let me know how you get on:

```java
// To serialize a ScanResult:
String jsonStr = scanResult.toJSON();  // or .toJSON(2) to indent the JSON

// To deserialize a ScanResult:
ScanResult scanResult = ScanResult.fromJSON(jsonStr);
```

Deserializing can be slower than scanning, due to the overhead of reflection, so in general if you just need a list of classes matching a certain criterion, rather than the full class graph, you should probably just save the list of names of matching classes, rather than serializing the whole ScanResult to disk.

**Comment by lukehutch** [comment]
I ran all unit tests through a serialize -> deserialize step, forcing them through the serializer and deserializer, and they all pass, so I pushed this out as version 3.1.0. However, I'm not closing this yet, because I want to put some solid instructions on the Wiki about how to do build-time scanning using Maven and Gradle.

**Comment by andrebrait** [comment]
Nice way to make sure the serializer/deserializer works hahaha

Ok, I'll grab it and see what I can do.

Oh, btw, isn't that 2 there a magic number?

Is there a constant for it? Or an an enum?

**Comment by andrebrait** [comment]
I assume that's what is usually called a pretty print, right?

**Comment by lukehutch** [comment]
@andrebrait The 2 is the indent width (0 for no indent, 1+ for prettyprinting, with that number of spaces per JSON indent depth). It's in the Javadoc, but I should make that clear in the docs too.

I got the Maven integration working, and documented it here:

https://github.com/lukehutch/fast-classpath-scanner/wiki/1.-Usage#build-time-scanning-serializing-scanresult-to-json

Feel free to send me a corresponding example for Gradle -- thanks again for your offer of helping with that. I'll close this bug for now though, since this feature is complete, working, and documented for Maven at least.

**Comment by lukehutch** [comment]
@cvmocanu Actually I just found a bug in the constructor lookup caching code in the deserializer, which is why it was going so slow. It's now faster to deserialize the JSON object graph that to perform the original classpath scan, so using a binary serializer probably wouldn't provide much additional benefit. The times I have for a large-ish classpath are:

```
Scan: 1.932 sec
Serialization: 1.128 sec (41.6% faster than scan)
Deserialization: 1.424 sec (26.3% faster than scan, 26% slower than serialization)
```

I'll push this out as version 3.1.1.

I thought of one other way to serialize a Java object graph that would be about as fast as possible: use a code generator to write code that builds the object graph directly using a set of constructor calls and field setting instructions or add()/put() method calls. So the serialized form of the object graph would be a classfile with a method that you would execute to reconstitute the object graph. I might work on that one day, but now that serialization and deserialization are faster than scanning, I'm happy with the state of things for the time being.

**Comment by cvmocanu** [comment]
Great news!

If you want to speed-up things even further, a (probably long term) idea is to minimize reflection.

That is: deserialize into an object tree that doesn't do any reflection, e.g. only keep the class / method / annotation names as String, without loading the classes or looking up the names.

Then provide an API that can be used to query this model.
Use reflection (and reflection caching) only for the results of the query.

In this way, if one is only interested in a few methods, only those classes will need to be loaded, not everything.

**Comment by lukehutch** [comment]
@cvmocanu something like that could work. As it is, I only ever look up a constructor or field once per class now, and that is cached using a HashTable, so the number of reflective calls is already minimal.

There are some other overheads of reflection though, such as getting the generic type information for a field or superclass, setting an array element, etc. -- and these cannot be eliminated without custom code generation. So I think that the current deserializer is (within 50% so) about as fast as it could be without resorting to custom code generation.

What you propose though is sort of related to what Reflections does by building a custom set of nested interfaces to represent packages, and then providing a way to query the class graph using static references to this faux class hierarchy:

https://github.com/ronmamo/reflections/blob/gh-pages/UseCases.md#serialize-reflections-into-a-java-source-file-and-use-it-to-statically-reference-java-elements

It's a cute trick, but I don't really see a huge benefit in doing this, other than possibly type safety, if you were to copy all the type information over to the faux class hierarchy (I'm not sure if Reflections even does that).

**Comment by johnou** [comment]
@andrebrait any luck with your Gradle integration?

**Comment by lukehutch** [comment]
For the record I just put the build-time scanning instructions into their own wiki page:

https://github.com/classgraph/classgraph/wiki/Build-Time-Scanning

This page has the Maven instructions, and then a link to Gradle instructions for doing the same sort of thing in Reflections. This should work more or less directly out of the box on Gradle. Would love to hear if this does work for anyone though.

BTW (off-topic) -- if anyone is a Gradle expert, and there would be a big win from moving ClassGraph from Maven to Gradle, I'd be happy to see that happen. Using Maven is a good way to drive oneself mad :-)

**Comment by mgood7123** [comment]
in light of this issue, does classgraph support android class scanning?

if so, are there any example/sample projects for android that demonstrate this?

**Comment by lukehutch** [comment]
@mgood7123 yes, see the same link I gave above, there is a Gradle example there that can be used for Android.
