### ISSUE TITLE
feature question

### ISSUE THREAD

**Issue by davidmoshal** [lukehutch/fast-classpath-scanner#187]
not a bug report: just curious if this library can be used to find  x, where:

private List<x> list_of_type_x;

**Comment by lukehutch** [comment]
Hi @davidmoshal -- I used to have an API call for exactly this usecase, but I removed it recently, since it seemed a bit esoteric, and I wasn't aware of anyone using it. The API had become way too complex, and I was looking for ways to simplify it.

What the API call did though was simply match all classes, then iterate through all fields of all classes looking for fields of the given type. You can still do that yourself, using something like the following (I think this is right, but I haven't tested it):

```java
for (final ClassInfo ci :
        new FastClasspathScanner(packageRoot)
            .enableFieldInfo()
            .ignoreFieldVisibility()
            .scan()
            .getClassNameToClassInfo()
            .values()) {
    for (final FieldInfo fi : ci.getFieldInfo()) {
        if (fi.getTypeStr().equals("List<String>")) {
            // ...
        }
    }
}
```

Let me know if this works for you.

**Comment by davidmoshal** [comment]
Thanks @lukehutch , I think you should put it back in!

The solution I came up with (btw this is groovy code):
```groovy
  classes.each { Class c ->

    c.declaredFields.each { Field f ->
      if (f.type == List) {
        List t = f.genericType [ 'actualTypeArguments' ]
        println "$f.name: $f.genericType ${t [ 0 ]}"
      }
    }
```

**Comment by lukehutch** [comment]
@davidmoshal The mechanism you chose requires all `Class` references to be instantiated for each class. Not only is this highly inefficient, you run the risk of triggering side effects if your classloader is configured to initialize classes (run initializer blocks) when the classes are loaded. The example I gave uses `ClassInfo` and `FieldInfo` object types (defined in the FCS project) rather than `Class` and `Field`. This is much faster, because only class metadata is read into those object types. I recommend trying to get the code snippet I gave above to work. 

BTW in addition to `getTypeStr()`, there are several other methods for fetching the type signature in the `FieldInfo` class.

As far as putting it back in -- I will soon be starting a major revamp of the API, in which you can filter classes on a range of flexible criteria. I'll make sure field attribute filtering is included in that API.

**Comment by davidmoshal** [comment]
thanks again @lukehutch , indeed this is exactly an issue I ran into:

> you run the risk of triggering side effects if your classloader is configured to initialize classes (run initializer blocks) when the classes are loaded

I had some initialization in a static initialization block which did indeed execute, good to know to avoid!

thanks again

David

**Comment by lukehutch** [comment]
@davidmoshal you can avoid initializing classes by passing `false` into `Class.forName()`: 

https://docs.oracle.com/javase/8/docs/api/java/lang/Class.html#forName-java.lang.String-boolean-java.lang.ClassLoader-

However, it's more complicated than that in general. You shouldn't do your own classloading, probably, you should call `ScanResult#classNameToClassRef(className)` to load a class given the class name. This will ensure that the class that is loaded is the same as the one whose class info is returned in the `ClassInfo` objects, in cases where there are multiple classes of the same name on the classpath, or where you override the `ClassLoader` passed to FCS, etc.  (This call also disables class initialization for you.)
