### ISSUE TITLE
A way to blacklist folders?

### ISSUE THREAD

**Issue by NogginBops** [lukehutch/fast-classpath-scanner#190]
Is there a way to blacklist all jars in a specific folder?

**Comment by lukehutch** [comment]
Not by way of the scan spec passed to the constructor. I could add something like that, but the scan spec syntax is already too complicated. The best thing to do is to get the current classpath, then remove the classpath entry that contains the offending jars, then scan with a custom classpath. Something like:

```java
ScanResult scanResult = new FastClasspathScanner()
    .overrideClasspath(
        new FastClasspathScanner()
            .getUniqueClasspathElements()
            .stream()
            .filter(p -> !p.endsWith("/bad-jar-dir")))
    .scan();
```

Does this work for you?

**Comment by lukehutch** [comment]
PS note that anytime you override the classpath, you run the risk of loading a different class than the one matched by FastClasspathScanner, since a class of the same name can be defined differently in two different locations on the classpath.

**Comment by lukehutch** [comment]
The above code snippet should hopefully work for you for now, but I'll merge this into the API improvements suggestion bug, #111.

**Comment by lukehutch** [comment]
@NogginBops I just pushed out version 2.20.1, with support for explicitly blacklisting classpath elements based on a string match criterion:

https://github.com/lukehutch/fast-classpath-scanner/releases/tag/fast-classpath-scanner-2.20.1

This will work better than the code snippet I gave above, since it applies the filtering before extracting jars-within-jars (in the case that you have classpath elements like `path/to/jar1.jar!/BOOT-INF/lib/jar2.jar`).
