### ISSUE TITLE
Enhancing the javadocs

### ISSUE THREAD

**Issue by andrebrait** [lukehutch/fast-classpath-scanner#191]
As of this moment, some things are a bit unexplained in the documentation like, say, the way ClassInfo stores class names. Is it the whole name? Is it the simple name? What's the equivalent in the usual Java Class API? 

Also making it clearer in the docs whether some method call results in using Reflection or not.

It's a very minor thing, of course, but it's an important one when developing without having yo switch to a browser window, etc.

I would do it for you and submit as a pull request, but since I'm waaaay too busy these days I'm submitting this. If I ever get the chance, I will help more.

**Comment by lukehutch** [comment]
@andrebrait You're totally right, the Javadocs need major polishing work. The library was not well documented in the beginning, and I went back a couple of times and added tons of Javadoc, but it really needs an end-to-end coverage, detail, and consistency check.

I'm going to be revamping the API in a major way soon, so I will hold off on redoing the Javadoc until then, because a large number of API methods will be going away and getting replaced by other methods of setting up scan criteria and reading the results.

I'll link this to the API rework bug, but will close it for now since that bug is tracking all the work that needs to be done on the API. Thanks for the suggestion! And thanks for the offer to help more when you have more time, that would be great!
