### ISSUE TITLE
Go TypeSafe :)

### ISSUE THREAD

**Issue by GedMarc** [lukehutch/fast-classpath-scanner#207]
Hey Luke,

Any chance of adding a type safe class fetcher?

public Class<?> classNameToClassRef(String className) throws IllegalArgumentException {
        return this.classNameToClassRef(className, false);
    }

public <T> Class<T> classNameToClassRef(String className,T type) throws IllegalArgumentException {
        return (Class<T>) this.classNameToClassRef(className, false);
    }

**Comment by GedMarc** [comment]
of course it removed all my `<T>`

**Comment by GedMarc** [comment]
```
@SuppressWarnings("unchecked")
public <T> Class<T> classNameToClassRef(String className,T type) throws IllegalArgumentException {
return (Class<T>) this.classNameToClassRef(className, false);
}
```

**Comment by andrebrait** [comment]
@GedMarc

I don't think it's possible.

Your last version requires the user to pass an object of the type as the last argument. Which is not viable.

```Class<Foo> fooClass = classNameToClassRef("Foo", new Foo());```

In any case, the class would have to be known and loaded already. Which defeats the whole point of scanning the classpath. If you already know the class and it's already loaded, you'd just use it.

**Comment by GedMarc** [comment]
Lol no, I think the purpose has been missed.

In the instance of using a Single Service the type is known, the implementation is not.
Using the ServiceLoader mechanism, the base implementation is for multiple implementations and not just one, so when mapping this produces the incorrect mechanism.
```
ClassType1 implements TypedService
ClassType2 implements TypedService

String requiredService = "Class1"
TypedService ts = classNameToClassRef("Class1",TypedService.class);
```
The only advantage this has over Class.forName() is that you don't have to catch ClassCastException and the class has to be in the scanned result set which is exactly what I want.

**Comment by andrebrait** [comment]
Oh, I see now.

Well, let's have Luke evaluate it :)

**Comment by lukehutch** [comment]
It makes sense to have this API, I think, for the case of implemented interfaces or superclasses, as @GedMarc pointed out, and it's pretty standard to do this -- although it's about the same amount of code to cast it yourself, as it is to pass the type in. I know casts are ugly, but they need to happen either inside or outside `classNameToClassRef()`. The only advantage here is that I could check if the passed type `.isAssignableFrom()` the loaded class, and then throw `IllegalArgumentException` rather than `ClassCastException` (but it's still an unchecked exception).

I'll add it, in case people want to use it as a matter of taste.

PS @GedMarc your first code example is not quite right: `<T> Class<T> classNameToClassRef(String className,T type)` should actually be `<T> Class<T> classNameToClassRef(String className, Class<T> type)`, otherwise the return type will be `Class<Class<T>>`.

**Comment by GedMarc** [comment]
This is great thanks Luke! Definitely a convenience implementation without a doubt, but reduces a good amount of boiler plate for me :)

I was having to iterate through returned service loaders, check if they were located in the scan result and implemented the service, then produce the class with type-casting from the scan result, and cast it back to the service type :)

It's like 40 lines down to 1 so thank you so much! Definitely not worth a seperate release but it certainly is incredibly convenient :)

**Comment by lukehutch** [comment]
@GedMarc sounds worthwhile then! Thanks for the request.
