### ISSUE TITLE
path scanner fails on windows

### ISSUE THREAD

**Issue by datasetutil** [lukehutch/fast-classpath-scanner#25]
root cause is nio.path issue on windows. Here is the Fix ClasspathFinder.java (line 75)

+        pathElementStr = System.getProperty( "os.name" ).contains( "indow" ) ? pathElementStr.substring(1) : pathElementStr;

**Comment by lukehutch** [comment]
Thanks for the bug report. I made some changes to paths recently, and I thought it might break Windows, but couldn't find a tester to test this. 

It looks like on Windows, you're getting paths like /c:/windows/file instead of c:\windows\file ? Can you please show me an example of what the incorrect path is, and what the correct one is?

It looks like even when URIs are encoded by Windows, they have a preceding '/' added, e.g. file:/c:/windows/path . That must mean there is a generic way to parse them too (the fix you gave looks a bit brittle...).

The top answer here looks right: http://stackoverflow.com/questions/6164448/convert-url-to-normal-windows-filename-java 

I'll try to patch my code with this soon, and I'll let you know so you can test.

**Comment by datasetutil** [comment]
Here is the full error stack in verbose:

FastClasspathScanner: Exception while trying to read classpath element /C:/Users/pgupta/.m2/repository/org/slf4j/slf4j-log4j12/1.6.6/slf4j-log4j12-1.6.6.jar : Illegal char <:> at index 2: /C:/Users/pgupta/.m2/repository/org/slf4j/slf4j-log4j12/1.6.6/slf4j-log4j12-1.6.6.jar
FastClasspathScanner: Exception while trying to read classpath element /C:/Users/pgupta/.m2/repository/log4j/log4j/1.2.17/log4j-1.2.17.jar : Illegal char <:> at index 2: /C:/Users/pgupta/.m2/repository/log4j/log4j/1.2.17/log4j-1.2.17.jar
FastClasspathScanner: Exception while trying to read classpath element /C:/Users/pgupta/.m2/repository/org/codehaus/jackson/jackson-mapper-asl/1.9.13/jackson-mapper-asl-1.9.13.jar : Illegal char <:> at index 2: /C:/Users/pgupta/.m2/repository/org/codehaus/jackson/jackson-mapper-asl/1.9.13/jackson-mapper-asl-1.9.13.jar
FastClasspathScanner: Exception while trying to read classpath element /C:/Users/pgupta/.m2/repository/org/codehaus/jackson/jackson-core-asl/1.9.13/jackson-core-asl-1.9.13.jar : Illegal char <:> at index 2: /C:/Users/pgupta/.m2/repository/org/codehaus/jackson/jackson-core-asl/1.9.13/jackson-core-asl-1.9.13.jar
FastClasspathScanner: Exception while trying to read classpath element /C:/Users/pgupta/.m2/repository/io/github/lukehutch/fast-classpath-scanner/1.9.5/fast-classpath-scanner-1.9.5.jar : Illegal char <:> at index 2: /C:/Users/pgupta/.m2/repository/io/github/lukehutch/fast-classpath-scanner/1.9.5/fast-classpath-scanner-1.9.5.jar
FastClasspathScanner: *** Starting scan ***
FastClasspathScanner: Classpath elements: []
FastClasspathScanner: Whitelisted paths:  [/]
FastClasspathScanner: Blacklisted paths:  []
FastClasspathScanner: *** Time taken by .scan(): 18 ms ***

**Comment by lukehutch** [comment]
Hi, I just pushed a potential fix to git, can you please test and let me know if this fixed it for you?

**Comment by lukehutch** [comment]
I pushed out 1.9.6 now too, in case it's easier for you to test using Maven rather than compiling from source.

**Comment by datasetutil** [comment]
Yes new release helped a lot. My unit test is now passing on windows. I am going to close the issue!

**Comment by lukehutch** [comment]
Great, thank you for testing!
