### ISSUE TITLE
Possible InputStream leak

### ISSUE THREAD

**Issue by drogatkin** [lukehutch/fast-classpath-scanner#27]
https://github.com/lukehutch/fast-classpath-scanner/blob/master/src/main/java/io/github/lukehutch/fastclasspathscanner/FastClasspathScanner.java#L1032
This method returns ArrayList, however I would prefer it returns just List or even Collection, to make it more portable when it is overridden.
I found opened input stream leak in my forked version and tried to switch to master branch to see if it is fixed, but I can't since certain methods signature was updated. If you fixed any open stream leak, please let me know..

**Comment by lukehutch** [comment]
Good catch, I didn't notice this. (Not sure why you'd want to subclass this class, but I'm happy to make the change, since it makes the API more consistent.)

**Comment by lukehutch** [comment]
Oops, reopening for stream leak issue. Can you specify what triggered the leak, i.e. what sort of MatchProcessor were you using?

**Comment by lukehutch** [comment]
PS I looked at all places where I'm opening streams in the current source, and all but one of them were using try-with-resources to auto-close their InputStreams. Only one usage (the DataInputStream in ClassfileBinary.readClassInfoFromClassfileHeader()) was not doing this. I didn't think it needed to close its stream, since it just wrapped a BufferedInputStream that wrapped the real InputStream for the file (which was itself auto-closed), but the DataInputStream is auto-closed now too, just in case on some weird system (e.g. Windows), a file handle is opened for wrapper stream or something.

So I may have fixed this between the version you were testing earlier, or maybe not closing the DataInputStream was causing the leak, but all streams are now auto-closed, so you should not see the leak anymore.

I would appreciate it if you could please test if you can, to verify if you're still seeing the leak. Sorry to change the method signatures, but there have been many fixes made in the last several months, so it would be useful to update to the latest version anyway. I think the project has become mature and stable now, so I plan to release a v2.0 soon (probably without any major changes) that will hopefully be usable long-term.

**Comment by drogatkin** [comment]
My bad, actually leak was in my class loader. However I fixed one place where ZipFile wasn't closed. I am not sure if it is required, but since the method is given I just assured calling it using try(){}

**Comment by lukehutch** [comment]
No worries -- where was ZipFile not being closed? Right now, the only place I open a ZipInputStream is in a try() block, so I assume this is fixed? Note that MatchProcessors don't have to close the stream when they're done, the stream is closed by the caller.

I'll assume this is fixed, so I'm closing the bug, but please reopen if you think I missed something. Thanks.
