### ISSUE TITLE
Feature discussion: Provide current search context to matcher

### ISSUE THREAD

**Issue by mtraut** [lukehutch/fast-classpath-scanner#33]
Hi Luke,

we recently tried to migrate homegrown code for our component container to your tool - thank you for providing it!

The only issue we're encountering so far is the fact that we need the context from where the match is encountered, because this "plugin" serves as another container for a new private classpath context. From here the plugin may lookup local content. 

Currently this is not possible as we do not have the context in the match processor. 

Do you think this might be a useful extension that could make it to the public API?

Greetings, Michael

**Comment by lukehutch** [comment]
Hi Michael, sounds useful, but what do you mean by "context"?

**Comment by mtraut** [comment]
Hi Luke,

sorry for being so vague (i'm well known for describing any software artifact with "context", "handler" and "wrapper" :-)).

We load plugins via classloader organized in directories

    root1
      + plugins
      |   + <context1>
      |   |   + PLUGIN-INF
      |   |   |  + plugin.xml
      |   |   + <plugin local data>
      |   + <context2>
      |   |   + PLUGIN-INF
      |   |   |  + plugin.xml
      |   |   + <plugin local data>
    root2
      + plugins
      |   + <context3>
      |   |   + PLUGIN-INF
      |   |   |  + plugin.xml
      |   |   + <plugin local data>
 
If i have a matcher to find me any "/plugins/*/plugin.xml" i am getting the relative path within a jar file or classes/ directory, not the root itself. So i can not setup a local classloader for the plugin.

Thanks for reading and merry xmas...

Michael

**Comment by lukehutch** [comment]
Ah, I see what you need. Funnily enough, the API used to give you the absolute path, not the relative path, and I figured nobody would need the absolute path, since the whole point of the classpath is to abstract away the absolute location of resources, so I removed it! However, I just added two new MatchProcessor types that provide you with the File object representing either the root of the classpath entry (if the classes are stored in the file hierarchy), or the zipfile (if the classes are stored in a jar/zip). This should do what you need. Please test, and re-open if it doesn't work for you, or if you need some other functionality. (I'll push a release out in half an hour or so once I make an unrelated change.) Merry Christmas!

**Comment by lukehutch** [comment]
Released in 1.9.13.

**Comment by mtraut** [comment]
Works as expected. Great - that's "responsive design", many thanks.

Design question: Wouldn't this have been a good candidate for a default method on the old interface?

**Comment by lukehutch** [comment]
Thanks for testing!

Probably that would work, yes, but I'm holding off on adding any more Java 8 features for now, since there is at least one user that needs this to work on JRE 1.7. (The only Java 8 feature I'm using right now is the FunctionalInterface annotation, which can be safely ignored by JRE 1.7 if you build using JDK 1.8 in Java 7 compatibility mode.)
