### ISSUE TITLE
FastClasspathScanner not finding classes under JBoss

### ISSUE THREAD

**Issue by Faliorn** [lukehutch/fast-classpath-scanner#43]
Hi!

First, I'd like to thank you for your effort at making FastClasspathScanner. It's just great and just what I needed!

However, when I deploy my application under JBoss 4.2.3.GA, it doesn't seem to be able to find any of my classes. The execution of getNamesOfAllClasses returns:

[GetoptDemo, gnu.getopt.Getopt, gnu.getopt.LongOpt, javax.management.MBeanServer, javax.management.MBeanServerBuilder, org.jboss.Main, org.jboss.Main$1, org.jboss.Main$JarFilter, org.jboss.Version, org.jboss.system.JBossRMIClassLoader, org.jboss.system.ORBSingleton, org.jboss.system.server.NoAnnotationURLClassLoader, org.jboss.system.server.Server, org.jboss.system.server.ServerConfig, org.jboss.system.server.ServerConfigUtil, org.jboss.system.server.ServerLoader, org.jboss.system.server.jmx.LazyMBeanServer, org.jboss.system.server.jmx.MBeanServerBuilderImpl, org.omg.CORBA_2_3.ORB]

Using the verbose method, the classpath elements are these:

Classpath elements: [F:\jboss-4.2.3.GA\client\getopt.jar, F:\jboss-4.2.3.GA\bin\run.jar]

It doesn't use the jars inside my EAR.

I've read the documentation and tried some different constructors, but still no luck. It would be great if you could help me with this.

Best regards and thanks again!

Faliorn

**Comment by lukehutch** [comment]
Hi Faliorn, thanks for trying out FastClasspathScanner, and for filing this bug report.

At one point I hacked together a really simple JBoss ClassLoader, based on someone's feature request:

https://github.com/lukehutch/fast-classpath-scanner/blob/master/src/main/java/io/github/lukehutch/fastclasspathscanner/scanner/classloaderhandler/JBossClassLoaderHandler.java

I did some very simple testing on it, and it seemed to work, but JBoss' module system is its own world, so I was pretty sure this wasn't completed...

I came across a mention of jboss-vfs, which is probably the right way to support JBoss:

https://github.com/lukehutch/fast-classpath-scanner/issues/37

However, I haven't looked into this any further.

I have close to zero experience with JBoss. Would you be interested in putting together a patch that fixes JBossClassLoaderHandler.java to use jboss-vfs? It could be a fun project, and contributions are greatly appreciated!

(It would be great if the patch used reflection to call the jboss-vfs API only if it was actually available on the classpath, since I don't want to add a hard dependency on JBoss to FastClasspathScanner.)

**Comment by lukehutch** [comment]
Incidentally, this is also related to the goal to get Java 9's modules supported in FastClasspathScanner, since those are based on JBoss modules, I think: https://github.com/lukehutch/fast-classpath-scanner/issues/36

**Comment by Faliorn** [comment]
Hi again.

Thanks for the ultra-fast answer. Although FastClasspathScanner seems more light-weight and powerful, I tried Reflections after that and it worked for the simple example I needed.

However I'll keep an eye on FastClasspathScanner, for I believe I might need more functionality soon, and it would be great if it worked with JBoss. As you, I have little experience against JBoss and wouldn't know how to start, so I can't help much at programming, but I could help with the testing.

Thanks and best regards!

**Comment by lukehutch** [comment]
That's good to know Reflections works for you with JBoss, that means their approach to supporting it is the correct one. I'll plan on borrowing their approach when I can get around to it, and I might ping you again to see if you'd be willing to test the code once that's done. I'll close this bug for now since there's already one about supporting JBoss properly. Thanks again for the report!

**Comment by lukehutch** [comment]
Hi, I just released a possible fix for this in 1.9.19, although I don't have full native JBoss support yet. If you have some spare time, any chance you could test again, please?
