### ISSUE TITLE
Disable Jar filters during development 

### ISSUE THREAD

**Issue by drekbour** [lukehutch/fast-classpath-scanner#49]
What do you recommend as the best way to apply a `jar:` filter so that the same code also works in the IDE (where no jar exists). I'm sure you are aware of the current behaviour; the existence of `jar:`completely disables normal classpath scanning. This is understandable but do you see a non-DIY solution to complex cases where some internal modules are loaded as IDE projects (no jars) and some left to dependency resolution to download
````java
new FastClasspathScanner("com.company.product","jar:com-company-module1.jar","jar:com-company-module2.jar"....)
````

**Comment by lukehutch** [comment]
This is tricky... is the reason for using a `jar:` filter to increase scanning speed, or something else? (If speed is not an issue, you should just whitelist the package prefix(es) that you use, rather than using a `jar:` prefix.)

**Comment by drekbour** [comment]
Yes, solely for performance and without any measurement that it would make a difference :). It's quite easy to end up with a lot of 3rd-party libs. I don't know how efficient FCS is at disregarding a jar based on a package whitelist...

**Comment by lukehutch** [comment]
Makes sense. Zipfiles tend to be fast to read when classfiles are not whitelisted, because the zip directory can be read quickly without reading zipfile content. (At least I'm assuming that Java does the right thing, and just reads the zip headers in creating ZipEntry objects, rather than uncompressing the whole file!) FastClasspathScanner only opens the FileInputStream on a ZipEntry for files in a zipfile that have a path that matches a whitelist entry.

I would be curious to see some numbers though, if you have a large project you can test (lots of 3rd party jars, with a small whitelist). If you turn on .verbose(), you'll see how many milliseconds were used to process each jarfile.

**Comment by lukehutch** [comment]
Scanning is faster now, whether classfiles are in a jar or in a directory. Please reopen this if your testing shows that the whitelist and/or blacklist criteria specification mechanisms don't do what you need to reduce scan time. Thanks!
