### ISSUE TITLE
Is there a way to disable all blacklisted packages and classes?

### ISSUE THREAD

**Issue by PascalSchumacher** [lukehutch/fast-classpath-scanner#60]
https://github.com/benas/random-beans allows you scan the classpath for concrete types if you like to generate random instances of beans with abstract field types. Sadly we are unable to upgrade to the latest version, because:

>Caused by: java.lang.IllegalArgumentException: Can't scan for java.lang.Comparable, it is in a >blacklisted package. You can explicitly override this by naming the class in the scan spec when you call the FastClasspathScanner constructor.
> at >io.github.lukehutch.fastclasspathscanner.FastClasspathScanner.checkClassNameIsNotBlacklisted(FastClasspathScanner.java:278)

Is there a way to disable all blacklists?

**Comment by lukehutch** [comment]
Hi @PascalSchumacher, thanks for the suggestion. I just added this feature (it is in git but not in a release yet -- I can push out a release once you have verified it works). From the docs:

* `new FastClasspathScanner("!", "com.x")`: Adding `"!"` to the scanning specification overrides the blacklisting of the system packages (`java.*` and `sun.*`), meaning classes in those packages can be used as match criteria. You will need this option if, for example, you are trying to find all classes that implement `java.lang.Comparable`, and you get the error `java.lang.IllegalArgumentException: Can't scan for java.lang.Comparable, it is in a blacklisted system package`. Note that if you disable system package blacklisting, you can scan for non-system classes that refer to system classes even if system jars are still blacklisted (e.g. if you add `"!"` to the spec, you can search for classes that implement `java.lang.Comparable` even though `java.lang.Comparable` is in a system jar, so won't itself be scanned). Adding `"!"` to the spec may increase the time and memory required to scan, since there are many references to system classes by non-system classes. 
* `new FastClasspathScanner("!!", "com.x")`: Adding `"!!"` to the spec overrides the blacklisting of the JRE system jars (`rt.jar` etc.), meaning those jars will be scanned, and also overrides the blacklisting of system packages (`java.*` and `sun.*`). You will need this option if you want to look for system classes that match a given criterion. Adding `"!!"` to the spec will increase the time and memory required to scan, since the system jars are large.  

Can you please test this and let me know if it works for you? Thanks!

**Comment by lukehutch** [comment]
This was released in 1.90.6, and I'm pretty sure it should do what you need, but please re-open this bug if it doesn't work for you -- thanks!

**Comment by PascalSchumacher** [comment]
Hi @lukehutch,

thank you very much. 

`"!!"` is exactly what we need. Scanning of system packages and classes works again. :+1: 

I guess the scanning between version `1.10.4` and version `1.90.7` changed regarding non-jar classes? When I use `new FastClasspathScanner("!!")` and then use `getNamesOfClassesImplementing()` or `classpathScanner.getNamesOfSubclassesOf()` to scan for classes in the test classpath it works in Eclipse, but fails when I run tests with maven from the command line. Do I now have to add an option to make this to work again? (I skimmed the documentation but found only https://github.com/lukehutch/fast-classpath-scanner#1-matching-the-subclasses-or-finding-the-superclasses-of-a-class but we are not using any whitelists.

**Comment by lukehutch** [comment]
Great, thanks for testing! Does "!" work as expected too? It seems like this would work shot the particular example toy provided, and it will be faster than "!!". 

Scanning should work the same in all contexts, assuming the classpath is the same. Can you please provide a minimal testcase that illustrates the problem?

**Comment by PascalSchumacher** [comment]
I did some further testing. Everything works fine on the unix buildserver. The problem occurs only on my windows laptop.

**Comment by lukehutch** [comment]
Ah, that's why I'm not seeing this, I don't have a Windows machine to test on, and as expected some things will be different in that environment. Please attach the output of calling `.verbose()` before `.scan()` so I can see what the classpath looks like on the Windows machine.

**Comment by PascalSchumacher** [comment]
https://github.com/PascalSchumacher/classpath-scanner-bug contains the example project and two files with verbose output.

**Comment by PascalSchumacher** [comment]
> Does "!" work as expected too?

Yes that works too. Thanks! :+1:

**Comment by lukehutch** [comment]
Great, thanks for verifying.

**Comment by lukehutch** [comment]
Sorry, didn't mean to close the bug, will look at your debug output this afternoon.

**Comment by lukehutch** [comment]
@PascalSchumacher Please check the latest commit (5a0c9e8), it hopefully fixes this problem for you.

**Comment by PascalSchumacher** [comment]
@lukehutch Thanks a lot for looking into this. Sadly it does not work yet. Here is the new log: https://github.com/PascalSchumacher/classpath-scanner-bug/blob/master/1.90.8-SNAPSHOT-verbose-output.txt

**Comment by lukehutch** [comment]
@PascalSchumacher oh man, this is tricky. I made some changes to remove the use of NIO's Path class, because it is slow, but now some things that work for Linux don't work for Windows, and vice versa. Will try to figure out the right approach to this.

**Comment by lukehutch** [comment]
@PascalSchumacher  OK, I think I finally fixed this in a9c2a505. Turns out the way the URL and URI classes parse things varies so much between operating systems that it's not worth relying on them for the harder parts of classpath URL/URI/path parsing. Please let me know if the latest head version works for you.

**Comment by PascalSchumacher** [comment]
Works fine now. :) Thank you very much!

**Comment by lukehutch** [comment]
Great, thanks for testing! I should push out a new release then, because scanning probably broke for other Windows users too.

**Comment by lukehutch** [comment]
Fixed in 1.90.8.
