### ISSUE TITLE
Docs: Chapter 9 refers to removed "FastClasspathScanner#classpathContentsModifiedSinceScan()"

### ISSUE THREAD

**Issue by jrehwaldt** [lukehutch/fast-classpath-scanner#66]
In the latest release the return value from `#scan()` was changed to `ScanResult`, which allows to request if classes were changed via `#classpathContentsModifiedSinceScan()`. The docs still describe the old API.

___
Question 1: Would it be possible to give `ScanResult` a `rescan()` method or is the desired way for rescanning to create or reuse a FastClasspathScanner? Maybe you could elaborate about this in the docs as well?
Question 2: Could you imagine to apply http://semver.org/ once version 2 is released? That is, indicate breaking API changes by increasing the major version number.

I can create separate tickets for those questions, if you want.

**Comment by lukehutch** [comment]
Hi, thanks for the report, and sorry about the breakage. There has been a lot of churn lately as I have been ramping up to the 2.0 release, but I should have been making these changes in another branch. I have been relying on version numbers in the second version field being >90 (e.g. "1.91.1") to give a soft warning of "beta status", but I never defined what that meant anywhere. Also, I have been bumping the second field, not the first field, for non-backwards-compatible API changes, which I see does not meet with common expectations.

My plan with the 2.0 release is for it to be a stable release, and hopefully one that does not require much ongoing maintenance. I'll definitely do my best to follow semver.org after the 2.0 release.

On your first question, you can reuse a single FastClasspathScanner instance. Each time you call `.scan()`, you get a new `ScanResult` object which you can query. (One reason for the change was to make repeated scanning much cleaner -- there is no reusing of state between scans now.) If you add `MatchProcessors` to FastClasspathScanner and you don't need the ScanResult, you can just ignore the return value each time you call `#scan()`, since the MatchProcessors are associated with the `FastClasspathScanner` instance, not the `ScanResult` instance.

`classpathContentsModifiedSinceScan()` is now a method on `ScanResult`, not on FastClasspathScanner`, because the timestamps of the files, directories and jars encountered during the scan are stored with the results of the scan. So if you do call `#scan()` multiple times, make sure you always call `classpathContentsModifiedSinceScan()` on the most recent `ScanResult` object. (I missed some of the references to this API change in a previous update to the documentation, but this should be fixed now.)

Thanks for pointing these issues out, and sorry again for causing you problems!

Quick survey question: what are you using FastClasspathScanner for?

**Comment by jrehwaldt** [comment]
Thank you for clarifying.

I build a simple CDI solution and found your library super easy. Also, it was one of the only libraries which properly supported Annotation scanning as required for the standard CDI scopes.

I plan to stay with your library whenever classpath scanning is required -- I am very pleased I found it. Thank you for it.

PS: Semver is mainly used in Web-Development (node/JavaScript). Nontheless, it is a good guideline. Feel free to specify your own semantic and clarify it in the README -- no need to insist on semver.

**Comment by lukehutch** [comment]
Great, glad it's working for you. Please keep the feedback coming if there's anything else you would like fixed or improved.
