### ISSUE TITLE
FCS can't find subclasses of java.lang.Object

### ISSUE THREAD

**Issue by alanfx** [lukehutch/fast-classpath-scanner#70]
I have recently reimplemented the classpath scanning functionality in the RadarGun project using FCS.[1] There is basically one method used to find classes that have a certain annotation that are in a specific package and|or subclasses of a specified class. The functionality all works at this point, but in a previous version I had issues if the caller passed `java.lang.Object` as the superclass. In this case, the call to `ScanResults.getNamesOfSubclassesOf` always returned zero items. I tried multiple things to fix this, including passing `java.lang.Object` to the `FastClasspathScanner` constructor, passing `!, java.lang.Object` to the `FastClasspathScanner` constructor, and passing `!!, java.lang.Object` to the `FastClasspathScanner` constructor. None of these made any difference. This is a minor issue, since asking for subclasses of `java.lang.Object` means you don't really care about the superclass, but I thought I would report it. Thanks for the code!

[1] https://github.com/radargun/radargun/blob/master/core/src/main/java/org/radargun/config/ClasspathScanner.java

**Comment by lukehutch** [comment]
Funny, I was specifically removing `java.lang.Object` from consideration, because it's such a common superclass, and I didn't think anyone would need to match it! But I see the value of being able to pass `java.lang.Object` in as a catch-all version of a parameter, so I just fixed this in master.

(Also note that there's always `FastClasspathScanner#matchAllClasses(ClassMatchProcessor classMatchProcessor)`, but then you have to filter out interfaces and annotations, and I see that sometimes you may want to switch to matching all standard classes as an option.)

I added a test, so this should work now, and I'll go ahead close the bug. With the fix, you do need to pass `"!"` into the constructor to allow this match case, because `java.lang.Object` is not only an "external" (non-scanned) class, but it is in the `java.lang` package, which is specifically blacklisted by default.

This should be in the next release, but please test and let me know if it fixes it for you.

**Comment by btbouwens** [comment]
Just cloned and tried to build, but I get
```
148753558-07-19T23:02+01	FastClasspathScanner	Completed scan (took 0.106885 sec)
Tests run: 3, Failures: 1, Errors: 1, Skipped: 0, Time elapsed: 0.939 sec <<< FAILURE!
testImplementsNamed(io.github.lukehutch.fastclasspathscanner.issues.IssuesTest)  Time elapsed: 0.039 sec  <<< ERROR!
java.lang.IllegalArgumentException: Can't scan for javax.inject.Named, it is in a blacklisted system package -- you can override this by adding "!" or "!!" to the scan spec to disable system package blacklisting or system jar blacklisting respectively (see the docs)
	at io.github.lukehutch.fastclasspathscanner.scanner.ScanSpec.checkClassIsNotBlacklisted(ScanSpec.java:478)
	at io.github.lukehutch.fastclasspathscanner.scanner.ScanSpec.getInterfaceName(ScanSpec.java:566)
	at io.github.lukehutch.fastclasspathscanner.scanner.ScanResult.getNamesOfClassesImplementing(ScanResult.java:262)
...

issue70(io.github.lukehutch.fastclasspathscanner.issues.IssuesTest)  Time elapsed: 0.885 sec  <<< FAILURE!
java.lang.AssertionError: 
Expecting
 <["ClassInDefaultPackage",
    "DefaultPackageTest",
    "com.apple.mrj.MRJAboutHandler",
    "com.apple.mrj.MRJApplicationUtils",
    "com.apple.mrj.MRJFileUtils",
...
    "org.junit.validator.PublicClassValidator",
    "org.junit.validator.TestClassValidator",
    "org.junit.validator.ValidateWith"]>
not to contain
 <["io.github.lukehutch.fastclasspathscanner.test.whitelisted.Impl1Sub"]>
but found
 <["io.github.lukehutch.fastclasspathscanner.test.whitelisted.Impl1Sub"]>

	at io.github.lukehutch.fastclasspathscanner.issues.IssuesTest.issue70(IssuesTest.java:33)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

....
Results :

Failed tests:   issue70(io.github.lukehutch.fastclasspathscanner.issues.IssuesTest): (..)

Tests in error: 
  testImplementsNamed(io.github.lukehutch.fastclasspathscanner.issues.IssuesTest): Can't scan for javax.inject.Named, it is in a blacklisted system package -- you can override this by adding "!" or "!!" to the scan spec to disable system package blacklisting or system jar blacklisting respectively (see the docs)

Tests run: 37, Failures: 1, Errors: 1, Skipped: 0

```

Do you require full details?

Bram

**Comment by lukehutch** [comment]
Dangit, yes, I pushed a change in the early hours of the morning, sorry about that. I have been meaning to add some git checkin hooks that run the tests before the code is checked in.

The issue here is whether you should be able to search for "external classes" (classes outside of your whitelisted packages), and whether external packages should be returned by queries. Currently you can search using blacklisted packages, as long as they are only one link in the classgraph away from whitelisted classes, but you don't get blacklisted classes back in results. I moved `javax.*` into the list of blacklisted system packages (along with `java.*` and `sun.*`, which were already there), and it broke this test.

This may also be related to why your superclass tests are failing in https://github.com/radargun/radargun/issues/373 .

The way I'll probably fix this is to add a `FastClasspathScanner#strictWhitelist()` method that disallows searching by blacklisted classes, and does not return non-whitelisted classes in results, and then switch off strictness by default.

I'll try to work on this tonight or tomorrow.

**Comment by lukehutch** [comment]
This should work now, sorry about the test breakage. By default, you can search for subclasses of `java.lang.Object`.

For the record (though you won't need this for your usecase), now if you call `FastClasspathScanner#strictWhitelist()` before `#scan()`, then external classes (classes referred to by whitelisted classes that are not themselves in a whitelisted package) are eliminated from returned results, and also cannot be used as matching criteria.

**Comment by lukehutch** [comment]
Note that `ScanResult#getNamesOfSubclassesOf("java.lang.Object")` returns only standard classes, not interfaces or annotations. Is that what you expect? (Technically interfaces have `java.lang.Object` as a superclass, according to the classfiles I looked at, but it seems more logical to return only standard classes as subclasses of `java.lang.Object`.)

**Comment by johnou** [comment]
Out of interest what is your use case for searching for subclasses of object?

**Comment by btbouwens** [comment]
That is not specifically my use case, I just tried to build, including the test.

However, for me it would be interesting to keep the direct subclasses of Object out of the graph, when they don't have subclasses. Just to keep the picture cleaner.

**Comment by lukehutch** [comment]
Oh, for that, couldn't you do something like the following?:

```
List<String> no subclasses = new FastClasspathScanner("com.pkg")
   .scan().getClassNameToClassInfo().values().stream()
   .filter(c -> !c.getSubClasses().isEmpty())
   .map(ClassInfo::getClassName()) 
   .collect(Collectors.toList());
```

**Comment by alanfx** [comment]
@johnou for me, the use case is as @lukehutch mentioned above. `Object.class` was a catch all, but it was easy to change that to use `null` instead. I think the main issue is that it is incorrect to return zero entries from `ScanResults.getNamesOfSubclassesOf(Object.class.getName())` when you pass "!" to the constructor.

And @lukehutch the code works for me with version `1.93.1`. Thanks!

**Comment by lukehutch** [comment]
Thanks for testing, @alanfx!
