### ISSUE TITLE
Multiple superclasses exception with Apache Kafka

### ISSUE THREAD

**Issue by gustavobilert** [lukehutch/fast-classpath-scanner#76]
Hi, I am trying to search files by extension:
```
    new FastClasspathScanner().matchFilenameExtension("avsc", new FileMatchContentsProcessor() {
            @Override
            public void processMatch(String relativePath, byte[] fileContents) throws IOException {
                System.out.println(relativePath);
            }
        }).scan();
```
I have Apache Kafka on the classpath, it is compiled in Scala, which has a kind of multiple inheritance, so FastClasspathScanner throws an exception complaining about **multiple superclasses**.
I do not need it to parse the Scala class model, just not to throw the exception or to provide a way to suppress it.
I have always wished for the capabilities you provide, please help make it compatible with our stack.

```
Exception in thread "main" java.lang.RuntimeException: java.lang.RuntimeException: Multiple superclasses of class kafka.consumer.Blacklist : [kafka.consumer.TopicFilter, scala.runtime.AbstractFunction1]
	at io.github.lukehutch.fastclasspathscanner.FastClasspathScanner.scan(FastClasspathScanner.java:939)
	at io.github.lukehutch.fastclasspathscanner.FastClasspathScanner.scan(FastClasspathScanner.java:963)
	at io.github.lukehutch.fastclasspathscanner.FastClasspathScanner.scan(FastClasspathScanner.java:982)
	at com.mycompany.Main.<init>(Bifrost.java:43)
	at com.mycompany.Main.main(Bifrost.java:90)
Caused by: java.lang.RuntimeException: Multiple superclasses of class kafka.consumer.Blacklist : [kafka.consumer.TopicFilter, scala.runtime.AbstractFunction1]
	at io.github.lukehutch.fastclasspathscanner.scanner.ClassInfo.addSuperclass(ClassInfo.java:361)
	at io.github.lukehutch.fastclasspathscanner.scanner.ClassInfoUnlinked.link(ClassInfoUnlinked.java:119)
	at io.github.lukehutch.fastclasspathscanner.scanner.Scanner.call(Scanner.java:328)
	at io.github.lukehutch.fastclasspathscanner.scanner.Scanner.call(Scanner.java:55)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by lukehutch** [comment]
Interesting.. I quickly hacked together basic Scala support previously, which fixed a problem for a previous bug reporter, but I always suspected there would be more issues lurking, because Scala does lots of weird stiff with "companion classes". 

Can you please put together a minimal standalone test case illustrating the problem, ideally with quick  instructions on how to set it up and run it in Eclipse (since  I know very little about Scala)? I do want to make sure Scala is properly supported. Thanks!

**Comment by gustavobilert** [comment]
I do not have any Scala code in my project, it is just the dependency to Kafka (using Gradle):
```
    // Kafka
    compile 'io.confluent:kafka-avro-serializer:1.0.1'
    compile ("org.apache.kafka:kafka_2.10:0.8.2.2") {
        exclude group: 'com.sun.jdmk', module: 'jmxtools'
        exclude group: 'com.sun.jmx', module: 'jmxri'
        exclude group: 'org.slf4j', module: 'slf4j-log4j12'
        exclude group: 'log4j', module: 'log4j'
    }
```
It is Kafka that comes compiled in Scala.
You should be able to reproduce it just having the dependency to it.

**Comment by lukehutch** [comment]
Thanks, I can duplicate it.

This is complicated... `scala.util.parsing.combinator.Parsers$Error$` has superclass `scala.runtime.AbstractFunction2`, but `scala.util.parsing.combinator.Parsers$Error` has superclass `scala.util.parsing.combinator.Parsers$NoSuccess`. The extra `$` on the end of `Parsers$Error$` is a companion class marker (there is also a suffix `...$class` that is used for other companion classes). I am merging companion classes together right now, so that you don't have to deal with more than one class name when using Scala classes, but maybe this indicates that I can't do that in general. I'm going to have to think about the right way to handle this, but unfortunately I don't know much about Scala, so I don't know what the expectation should be. Do you have good knowledge of Scala?

**Comment by lukehutch** [comment]
Hi, this exception is removed in  2.0.2, which should fix your problem. I added some additional methods in this release that allow this to be dealt with on a case-by-case basis. Upgrading to 2.0.2 should fix your problem. I'll close this bug, because the exception doesn't even exist anymore, so it won't be thrown, but please comment here to confirm that it's working for you now.

**Comment by gustavobilert** [comment]
It worked, thank you!

I have studied Scala a bit, but I am not using it.
If you want to support it, I think you need to consider its type system (http://docs.scala-lang.org/tutorials/tour/unified-types.html) and also its multiple-inheritance mechanisms like Traits and Mixins (http://docs.scala-lang.org/tutorials/tour/mixin-class-composition).
The hard part is that you will not see these structures directly, but only the crazy bytecode it generates.

**Comment by lukehutch** [comment]
@gustavobilert Thanks for the links. It is exactly mixins that caused this problem. Since Java has only a single inheritance model, Scala compiles two classes (or sometimes three), with slightly different name variations (it adds the suffix "$" or "$class" to the name). FastClasspathScanner merges these into the same `ClassInfo` object. I just removed the restriction of having just one superclass, but added methods that expect a single superclass for cases where that is the most likely scenario (i.e. for regular Java).

It is highly likely Scala does other weird things that I'm not handling properly. If you or anyone else comes across these, please file additional bug reports. Thanks!
