### ISSUE TITLE
Nullpointer exception caused by JbossClassLoaderHandler

### ISSUE THREAD

**Issue by msteur** [lukehutch/fast-classpath-scanner#81]
The path name for a resource loader is not always set . 
This at least seems to be the case for build in modules like the jee libraries.
This occured on wildfly 10.0.0.Final.

Because of this, this line result in a null value:
`final String pathElement = (String) ReflectionUtils.invokeMethod(root, "getPathName");`
This results in a nullpointer exception later on when a new ClasspathRelativePath instance is created.

A simple null check before adding the class path element at least prevents the exception and allows it to scan my own code.

**Comment by lukehutch** [comment]
Thanks for reporting this, and for backtracking back through the code to figure out where the problem was triggered -- great sleuthing!

This specific problem should be fixed in the head revision, please test and let me know if this is fixed for you, and go ahead and close the bug if it is fixed for you.

JBoss support is not thoroughly tested, so please report any additional problems you encounter. Thanks!

**Comment by msteur** [comment]
This seems to be working. Thanks for the quick fix!

**Comment by lukehutch** [comment]
Released in version 2.0.4.
