### ISSUE TITLE
What's the status of this project?

### ISSUE THREAD

**Issue by gembin** [lukehutch/fast-classpath-scanner#9]
Thanks for your great work, it looks interesting.

This is a question rather than an issue.
Is it production ready? And how it is compare to other libraries, like [reflections](https://github.com/ronmamo/reflections).

**Comment by lukehutch** [comment]
I believe it is production ready. I use it myself in a large, complex project without issues. The github project has quite a lot of stars, and a few forks, if that's any indication -- I know the library is in use in several places without issue.

I released 1.0 when I thought it was ready for production. A few minor bugs and feature requests have been filed since them, and I have tried to fix them within 24 hours or so whenever possible. I periodically look at all the branches to pull in the best changes from other people's branches (where they have added a feature or fixed a bug without sending them to me directly).

I don't have anything on my TODO list currently, I believe it's more or less feature complete and (fingers crossed!)  "bug free" ;) 

Hope that helps!

**Comment by lukehutch** [comment]
PS I haven't compared this library to Reflections -- that looks like quite a nice library. I suspect my library is faster,  since I paid a lot of attention to speed, but that may not matter for your use case. It looks like Reflections can fetch from URIs (which mine can't, since it's classpath-focuse anyway), and (in that case at least) can do so in parallel.

**Comment by lukehutch** [comment]
If you do compare this library to Reflections, please report back on your findings. Thanks, and I hope Fast Classpath Scanner works well for you!

**Comment by gembin** [comment]
Really appreciate for your such detailed answer. I will give it a try.

BTW: why not add the maven dependency to the README.md,    : - )

```xml
<dependency>
	<groupId>io.github.lukehutch</groupId>
	<artifactId>fast-classpath-scanner</artifactId>
	<version>latest_version</version>
</dependency>
```

**Comment by lukehutch** [comment]
Thanks, I appreciate the suggestion. I also put a link to Reflections in my README.md as a possible alternative in case it works better for people.
