### ISSUE TITLE
Whitelist issue

### ISSUE THREAD

**Issue by tenebras** [lukehutch/fast-classpath-scanner#95]
Good day,

probably I'm doing something wrong, but when I try to whitelist some classes it doesn't work as expected.

I want to limit scanner to find only three classes and then get annotated with some annotation. 
Here example of what I'm trying to do:

```
package com.somepackage;
...

List<String> annotatedClasses = new FastClasspathScanner(
		"com.somepackage.TestHandler1.class", 
		"com.somepackage.TestHandler2.class", 
		"com.somepackage.TestService.class"
	)
	.scan()
	.getNamesOfClassesWithAnnotation(RpcHandler.class);

@RpcHandler
class TestHandler1{}

@RpcHandler
class TestHandler2{}

@RpcHandler
class TestHandler3{}

class TestService{}
```

`annotatedClasses` should contain only two records. But in real it has three :(. 
When I add class name with full name (with package) this package becomes whitelisted and as result every class in it whitelisted.

Update: Version 1.9.20

Thanks, Alexander

**Comment by lukehutch** [comment]
Hi Alexander / @tenebras,

Version 1.9.20 is very old, and many bugs have been fixed. Can you please update to the latest version (2.0.9) and test again?

Also, you don't need the `.class` suffix on the end of class names. Please try without this. You'll see that the examples in the documentation don't have this. This is important both because there is no class with the names you listed, but also because FCS uses the capitalization after the last dot to decide if it's looking at a class name or a package name, and since `.class` has a lowercase `c`, it will think this is a package name, not a class name.

When I test this on the latest version of FCS, I get exactly two results: `com.somepackage.TestHandler1` and `com.somepackage.TestHandler2`.

**Comment by tenebras** [comment]
Sorry didn't checked latest version. Yes, it works with 2.0.9. 

I guess in 1.9.20 was something to trim `.class` suffix before package/class detection. Any way I added suffix for test purposes only.

Thank you!

**Comment by lukehutch** [comment]
OK, thanks for the report, that's good that it works for you now.
